In [2]:
import numpy as np
import pandas as pd

In [3]:
df=pd.read_excel('Labelled_DATA(1).xlsx')
df

Case No. Unnamed: 1 Aceto Image Name      Vessel Image Name  \
0           1        NaN              NaN                    NaN   
1           2        NaN              NaN  2.1_2.jpg , 2.2_4.jpg   
2           3        NaN              NaN                    NaN   
3           4        NaN              NaN              4.2_4.jpg   
4           5        NaN              NaN              5.1_1.jpg   
..        ...        ...              ...                    ...   
386       387        AAR         AAR1.jpg                    NaN   
387       388        AEY         AEY1.jpg                    NaN   
388       389        AEU         AEU1.jpg                    NaN   
389       390        ADF         ADF1.jpg                    NaN   
390       391        ABK         ABK1.jpg                    NaN   

     Lugol Image Name  Unnamed: 5  Aceto Uptake  Margins  Vessels  \
0                 NaN         NaN           2.0      NaN      NaN   
1             2_5.jpg         NaN           2.0      2.0      1.0   
2             3_3.jpg         NaN           2.0      NaN      NaN   
3             4_5.jpg         NaN           2.0      NaN      2.0   
4             5_4.jpg         NaN           2.0      NaN      1.0   
..                ...         ...           ...      ...      ...   
386               NaN         NaN           2.0      NaN      NaN   
387               NaN         NaN           2.0      NaN      NaN   
388               NaN         NaN           2.0      NaN      NaN   
389               NaN         NaN           2.0      NaN      NaN   
390               NaN         NaN           2.0      NaN      NaN   

     Lesion Size  Iodine Uptake  Unnamed: 11  Swede Score  
0            NaN            NaN          NaN          NaN  
1            1.0            2.0          NaN          8.0  
2            NaN            2.0          NaN          9.0  
3            NaN            2.0          NaN         10.0  
4            NaN            2.0          NaN          9.0  
..           ...            ...          ...          ...  
386          NaN            NaN          NaN          NaN  
387          NaN            NaN          NaN          NaN  
388          NaN            NaN          NaN          NaN  
389          NaN            NaN          NaN          NaN  
390          NaN            NaN          NaN          NaN  

[391 rows x 13 columns]

In [4]:
df.columns

Index(['Case No.', 'Unnamed: 1', 'Aceto Image Name', 'Vessel Image Name',
       ' Lugol Image Name', 'Unnamed: 5', 'Aceto Uptake', 'Margins', 'Vessels',
       'Lesion Size', 'Iodine Uptake', 'Unnamed: 11', 'Swede Score'],
      dtype='object')

In [5]:
df_img=df[[" Lugol Image Name","Iodine Uptake"]]
df_img

Lugol Image Name  Iodine Uptake
0                 NaN            NaN
1             2_5.jpg            2.0
2             3_3.jpg            2.0
3             4_5.jpg            2.0
4             5_4.jpg            2.0
..                ...            ...
386               NaN            NaN
387               NaN            NaN
388               NaN            NaN
389               NaN            NaN
390               NaN            NaN

[391 rows x 2 columns]

In [6]:
df_img=df_img.dropna()
df_img

Lugol Image Name  Iodine Uptake
1             2_5.jpg            2.0
2             3_3.jpg            2.0
3             4_5.jpg            2.0
4             5_4.jpg            2.0
5             6_4.jpg            2.0
..                ...            ...
358          AEH2.jpg            2.0
359          AAM2.jpg            2.0
367          ABX2.jpg            2.0
368          ADS2.jpg            2.0
370          APW2.jpg            2.0

[106 rows x 2 columns]

In [7]:
def update_img_name(img_name):
    return img_name.replace('.jpg', '_in_crop1.jpg')
df_img[' Lugol Image Name'] = df_img[' Lugol Image Name'].apply(update_img_name)

C:\Users\sakth\AppData\Local\Temp\ipykernel_8620\1064419030.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_img[' Lugol Image Name'] = df_img[' Lugol Image Name'].apply(update_img_name)


In [8]:
df_img

Lugol Image Name  Iodine Uptake
1     2_5_in_crop1.jpg            2.0
2     3_3_in_crop1.jpg            2.0
3     4_5_in_crop1.jpg            2.0
4     5_4_in_crop1.jpg            2.0
5     6_4_in_crop1.jpg            2.0
..                 ...            ...
358  AEH2_in_crop1.jpg            2.0
359  AAM2_in_crop1.jpg            2.0
367  ABX2_in_crop1.jpg            2.0
368  ADS2_in_crop1.jpg            2.0
370  APW2_in_crop1.jpg            2.0

[106 rows x 2 columns]

In [9]:
df_img.rename(columns={" Lugol Image Name": "Image Name"},inplace=True)
df_img

C:\Users\sakth\AppData\Local\Temp\ipykernel_8620\1156118783.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_img.rename(columns={" Lugol Image Name": "Image Name"},inplace=True)


Image Name  Iodine Uptake
1     2_5_in_crop1.jpg            2.0
2     3_3_in_crop1.jpg            2.0
3     4_5_in_crop1.jpg            2.0
4     5_4_in_crop1.jpg            2.0
5     6_4_in_crop1.jpg            2.0
..                 ...            ...
358  AEH2_in_crop1.jpg            2.0
359  AAM2_in_crop1.jpg            2.0
367  ABX2_in_crop1.jpg            2.0
368  ADS2_in_crop1.jpg            2.0
370  APW2_in_crop1.jpg            2.0

[106 rows x 2 columns]

In [10]:
glcm= pd.read_excel('glc_cin.xlsx')
glcm

Image Name    Contrast  Dissimilarity  Homogeneity    Energy  \
0     12_5_in_crop1.jpg   84.690826       3.455332     0.592199  0.442344   
1     14_8_in_crop1.jpg  100.318181       4.141644     0.546785  0.439311   
2     15_3_in_crop1.jpg   46.868698       2.136087     0.638059  0.438082   
3     16_5_in_crop1.jpg   83.807463       3.456763     0.609191  0.439490   
4    173_2_in_crop1.jpg   26.063500       1.730971     0.632143  0.306770   
..                  ...         ...            ...          ...       ...   
101   AEN2_in_crop1.jpg   31.829377       1.751034     0.703008  0.576935   
102   AEO2_in_crop1.jpg   66.153792       2.392307     0.715254  0.582067   
103   AEP2_in_crop1.jpg   60.808640       2.327219     0.703013  0.579869   
104   AES2_in_crop1.jpg   79.503855       2.506181     0.698602  0.576119   
105   AFB2_in_crop1.jpg   67.207705       2.027358     0.715219  0.574479   

     Correlation   Entropy  
0       0.987670  5.072308  
1       0.988555  5.115502  
2       0.994615  5.255445  
3       0.989705  5.161599  
4       0.990653  5.376216  
..           ...       ...  
101     0.995241  4.103278  
102     0.989680  4.131880  
103     0.990826  4.108394  
104     0.991145  3.993880  
105     0.995334  3.913479  

[106 rows x 7 columns]

In [11]:
final=pd.merge(glcm, df_img, on='Image Name')
final

Image Name    Contrast  Dissimilarity  Homogeneity    Energy  \
0     12_5_in_crop1.jpg   84.690826       3.455332     0.592199  0.442344   
1     14_8_in_crop1.jpg  100.318181       4.141644     0.546785  0.439311   
2     15_3_in_crop1.jpg   46.868698       2.136087     0.638059  0.438082   
3     16_5_in_crop1.jpg   83.807463       3.456763     0.609191  0.439490   
4    173_2_in_crop1.jpg   26.063500       1.730971     0.632143  0.306770   
..                  ...         ...            ...          ...       ...   
98    AEN2_in_crop1.jpg   31.829377       1.751034     0.703008  0.576935   
99    AEO2_in_crop1.jpg   66.153792       2.392307     0.715254  0.582067   
100   AEP2_in_crop1.jpg   60.808640       2.327219     0.703013  0.579869   
101   AES2_in_crop1.jpg   79.503855       2.506181     0.698602  0.576119   
102   AFB2_in_crop1.jpg   67.207705       2.027358     0.715219  0.574479   

     Correlation   Entropy  Iodine Uptake  
0       0.987670  5.072308            2.0  
1       0.988555  5.115502            2.0  
2       0.994615  5.255445            2.0  
3       0.989705  5.161599            2.0  
4       0.990653  5.376216            1.0  
..           ...       ...            ...  
98      0.995241  4.103278            2.0  
99      0.989680  4.131880            2.0  
100     0.990826  4.108394            0.0  
101     0.991145  3.993880            2.0  
102     0.995334  3.913479            2.0  

[103 rows x 8 columns]

In [12]:
X=final.iloc[:,1:7]
X.head()


Contrast  Dissimilarity  Homogeneity    Energy  Correlation   Entropy
0   84.690826       3.455332     0.592199  0.442344     0.987670  5.072308
1  100.318181       4.141644     0.546785  0.439311     0.988555  5.115502
2   46.868698       2.136087     0.638059  0.438082     0.994615  5.255445
3   83.807463       3.456763     0.609191  0.439490     0.989705  5.161599
4   26.063500       1.730971     0.632143  0.306770     0.990653  5.376216

In [13]:

Y=final["Iodine Uptake"]
Y.head()


0    2.0
1    2.0
2    2.0
3    2.0
4    1.0
Name: Iodine Uptake, dtype: float64

In [14]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test= train_test_split(X,Y, random_state=100, test_size=0.2)
y_train.head()

import time
from sklearn.svm import SVC 
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
svm = SVC(kernel = 'linear', C = 1)
svm.fit(x_train, y_train) 
start=time.time()
svm_predictions = svm.predict(x_test) 
# model accuracy for X_test   
accuracy = svm.score(x_test, y_test)

# creating a confusion matrix 
cm = confusion_matrix(y_test, svm_predictions) 
print("Accuracy of SVM is:",accuracy)
end=time.time()
print("Time taken:", end - start) 
print(cm)


Accuracy of SVM is: 0.6190476190476191
Time taken: 0.012138605117797852
[[ 0  0  5]
 [ 0  0  1]
 [ 0  2 13]]


In [16]:

from sklearn.ensemble import RandomForestClassifier
model=RandomForestClassifier(n_estimators=25)
model.fit(x_train,y_train)
preds=model.predict(x_test)
acc=accuracy_score(y_test,preds)
print("The Accuracy of randomforestclassifier is:", acc)

parameters = {
    "n_estimators":[5,10,50,100,250],
    "max_depth":[2,4,8,16,32,None]
}

from sklearn.model_selection import GridSearchCV
cv = GridSearchCV(model,parameters,cv=5)
start=time.time()
cv.fit(x_train,y_train)
end=time.time()
print("The best accuracy score obtained is:",cv.best_score_," at parameters ", cv.best_params_)
print("Time taken:", end-start)


The Accuracy of randomforestclassifier is: 0.7142857142857143


c:\Users\sakth\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\model_selection\_split.py:725: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(


The best accuracy score obtained is: 0.7308823529411764  at parameters  {'max_depth': 16, 'n_estimators': 50}
Time taken: 25.35868263244629


In [17]:


from sklearn.ensemble import RandomForestClassifier
model=RandomForestClassifier(n_estimators=50)
model.fit(x_train,y_train)
preds=model.predict(x_test)
acc=accuracy_score(y_test,preds)
print("The Accuracy of randomforestclassifier is:", acc)
cm = confusion_matrix(y_test, preds) 
print(cm)


The Accuracy of randomforestclassifier is: 0.7619047619047619
[[ 4  0  1]
 [ 0  0  1]
 [ 3  0 12]]


In [18]:

from sklearn.ensemble import GradientBoostingClassifier

model= GradientBoostingClassifier()
start=time.time()
model.fit(x_train,y_train)
end=time.time()
preds=model.predict(x_test)
acc=accuracy_score(y_test, preds)
print("Accuracy:", acc)
print("Time taken:", end-start)
cm = confusion_matrix(y_test, preds) 
print(cm)


Accuracy: 0.7619047619047619
Time taken: 0.5263535976409912
[[ 4  0  1]
 [ 0  0  1]
 [ 3  0 12]]


In [19]:

from sklearn.naive_bayes import GaussianNB
model=GaussianNB()
start=time.time()
model.fit(x_train,y_train)
end=time.time()
preds=model.predict(x_test)
acc=accuracy_score(y_test,preds)
print("The Accuracy of Naive Bayes is:", acc)
print("Time:", end-start)
cm = confusion_matrix(y_test, preds) 
print(cm)


The Accuracy of Naive Bayes is: 0.6666666666666666
Time: 0.0025496482849121094
[[ 4  0  1]
 [ 0  0  1]
 [ 5  0 10]]


In [21]:

from sklearn.linear_model import LogisticRegression
model=LogisticRegression()
start=time.time()
model.fit(x_train,y_train)
end=time.time()
preds=model.predict(x_test)
acc=accuracy_score(y_test,preds)
print("The Accuracy of Logistic regression is:", acc)
print("Time:", end-start)
cm = confusion_matrix(y_test, preds) 
print(cm)


The Accuracy of Logistic regression is: 0.5714285714285714
Time: 0.04847288131713867
[[ 0  0  5]
 [ 0  0  1]
 [ 1  2 12]]


c:\Users\sakth\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [15]:

final=final[final["Iodine Uptake"]!=1.0]
final


Image Name    Contrast  Dissimilarity  Homogeneity    Energy  \
0     12_5_in_crop1.jpg   84.690826       3.455332     0.592199  0.442344   
1     14_8_in_crop1.jpg  100.318181       4.141644     0.546785  0.439311   
2     15_3_in_crop1.jpg   46.868698       2.136087     0.638059  0.438082   
3     16_5_in_crop1.jpg   83.807463       3.456763     0.609191  0.439490   
7    176_2_in_crop1.jpg   80.286325       3.502934     0.503538  0.300409   
..                  ...         ...            ...          ...       ...   
98    AEN2_in_crop1.jpg   31.829377       1.751034     0.703008  0.576935   
99    AEO2_in_crop1.jpg   66.153792       2.392307     0.715254  0.582067   
100   AEP2_in_crop1.jpg   60.808640       2.327219     0.703013  0.579869   
101   AES2_in_crop1.jpg   79.503855       2.506181     0.698602  0.576119   
102   AFB2_in_crop1.jpg   67.207705       2.027358     0.715219  0.574479   

     Correlation   Entropy  Iodine Uptake  
0       0.987670  5.072308            2.0  
1       0.988555  5.115502            2.0  
2       0.994615  5.255445            2.0  
3       0.989705  5.161599            2.0  
7       0.982594  5.932345            2.0  
..           ...       ...            ...  
98      0.995241  4.103278            2.0  
99      0.989680  4.131880            2.0  
100     0.990826  4.108394            0.0  
101     0.991145  3.993880            2.0  
102     0.995334  3.913479            2.0  

[98 rows x 8 columns]

In [16]:


X=final.iloc[:,1:7]
X.head()


Contrast  Dissimilarity  Homogeneity    Energy  Correlation   Entropy
0   84.690826       3.455332     0.592199  0.442344     0.987670  5.072308
1  100.318181       4.141644     0.546785  0.439311     0.988555  5.115502
2   46.868698       2.136087     0.638059  0.438082     0.994615  5.255445
3   83.807463       3.456763     0.609191  0.439490     0.989705  5.161599
7   80.286325       3.502934     0.503538  0.300409     0.982594  5.932345

In [17]:


Y=final["Iodine Uptake"]
Y.head()



0    2.0
1    2.0
2    2.0
3    2.0
7    2.0
Name: Iodine Uptake, dtype: float64

In [18]:


from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test= train_test_split(X,Y, random_state=100, test_size=0.2)
y_train.head()




25    2.0
28    2.0
10    2.0
3     2.0
45    0.0
Name: Iodine Uptake, dtype: float64

In [19]:

import time
from sklearn.svm import SVC 
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
svm = SVC(kernel = 'linear', C = 1)
svm.fit(x_train, y_train) 
start=time.time()
svm_predictions = svm.predict(x_test) 
# model accuracy for X_test   
accuracy = svm.score(x_test, y_test)

# creating a confusion matrix 
cm = confusion_matrix(y_test, svm_predictions) 
print("Accuracy of SVM is:",accuracy)
end=time.time()
print("Time taken:", end - start) 
print(cm)



Accuracy of SVM is: 0.85
Time taken: 0.0
[[ 0  3]
 [ 0 17]]


In [20]:


from sklearn.ensemble import RandomForestClassifier
model=RandomForestClassifier(n_estimators=25)
model.fit(x_train,y_train)
preds=model.predict(x_test)
acc=accuracy_score(y_test,preds)
print("The Accuracy of randomforestclassifier is:", acc)

parameters = {
    "n_estimators":[5,10,50,100,250],
    "max_depth":[2,4,8,16,32,None]
}

from sklearn.model_selection import GridSearchCV
cv = GridSearchCV(model,parameters,cv=5)
start=time.time()
cv.fit(x_train,y_train)
end=time.time()
print("The best accuracy score obtained is:",cv.best_score_," at parameters ", cv.best_params_)
print("Time taken:", end-start)



The Accuracy of randomforestclassifier is: 0.8
The best accuracy score obtained is: 0.7183333333333334  at parameters  {'max_depth': 2, 'n_estimators': 5}
Time taken: 17.138795375823975


In [21]:


from sklearn.ensemble import RandomForestClassifier
model=RandomForestClassifier(n_estimators=50, max_depth=16)
model.fit(x_train,y_train)
preds=model.predict(x_test)
acc=accuracy_score(y_test,preds)
print("The Accuracy of randomforestclassifier is:", acc)
cm = confusion_matrix(y_test, preds) 
print(cm)



The Accuracy of randomforestclassifier is: 0.85
[[ 2  1]
 [ 2 15]]


In [22]:


from sklearn.ensemble import GradientBoostingClassifier
import pickle
model= GradientBoostingClassifier()
start=time.time()
model.fit(x_train,y_train)
end=time.time()
preds=model.predict(x_test)
acc=accuracy_score(y_test, preds)
print("Accuracy:", acc)
print("Time taken:", end-start)
cm = confusion_matrix(y_test, preds) 
print(cm)
pickle.dump(model, open("lugols_in_crop_gbt","wb"))




Accuracy: 0.85
Time taken: 0.19696331024169922
[[ 2  1]
 [ 2 15]]


In [23]:

from sklearn.naive_bayes import GaussianNB
model=GaussianNB()
start=time.time()
model.fit(x_train,y_train)
end=time.time()
preds=model.predict(x_test)
acc=accuracy_score(y_test,preds)
print("The Accuracy of Naive Bayes is:", acc)
print("Time:", end-start)
cm = confusion_matrix(y_test, preds) 
print(cm)



The Accuracy of Naive Bayes is: 0.7
Time: 0.003999948501586914
[[ 3  0]
 [ 6 11]]


In [24]:


from sklearn.linear_model import LogisticRegression
model=LogisticRegression()
start=time.time()
model.fit(x_train,y_train)
end=time.time()
preds=model.predict(x_test)
acc=accuracy_score(y_test,preds)
print("The Accuracy of Logistic regression is:", acc)
print("Time:", end-start)
cm = confusion_matrix(y_test, preds) 
print(cm)

The Accuracy of Logistic regression is: 0.8
Time: 0.029876708984375
[[ 0  3]
 [ 1 16]]
