In [12]:
import numpy as np
import pandas as pd

In [13]:
df=pd.read_excel('Labelled_DATA(1).xlsx')
df

Case No. Unnamed: 1 Aceto Image Name      Vessel Image Name  \
0           1        NaN              NaN                    NaN   
1           2        NaN              NaN  2.1_2.jpg , 2.2_4.jpg   
2           3        NaN              NaN                    NaN   
3           4        NaN              NaN              4.2_4.jpg   
4           5        NaN              NaN              5.1_1.jpg   
..        ...        ...              ...                    ...   
386       387        AAR         AAR1.jpg                    NaN   
387       388        AEY         AEY1.jpg                    NaN   
388       389        AEU         AEU1.jpg                    NaN   
389       390        ADF         ADF1.jpg                    NaN   
390       391        ABK         ABK1.jpg                    NaN   

     Lugol Image Name  Unnamed: 5  Aceto Uptake  Margins  Vessels  \
0                 NaN         NaN           2.0      NaN      NaN   
1             2_5.jpg         NaN           2.0      2.0      1.0   
2             3_3.jpg         NaN           2.0      NaN      NaN   
3             4_5.jpg         NaN           2.0      NaN      2.0   
4             5_4.jpg         NaN           2.0      NaN      1.0   
..                ...         ...           ...      ...      ...   
386               NaN         NaN           2.0      NaN      NaN   
387               NaN         NaN           2.0      NaN      NaN   
388               NaN         NaN           2.0      NaN      NaN   
389               NaN         NaN           2.0      NaN      NaN   
390               NaN         NaN           2.0      NaN      NaN   

     Lesion Size  Iodine Uptake  Unnamed: 11  Swede Score  
0            NaN            NaN          NaN          NaN  
1            1.0            2.0          NaN          8.0  
2            NaN            2.0          NaN          9.0  
3            NaN            2.0          NaN         10.0  
4            NaN            2.0          NaN          9.0  
..           ...            ...          ...          ...  
386          NaN            NaN          NaN          NaN  
387          NaN            NaN          NaN          NaN  
388          NaN            NaN          NaN          NaN  
389          NaN            NaN          NaN          NaN  
390          NaN            NaN          NaN          NaN  

[391 rows x 13 columns]

In [14]:
df.columns

Index(['Case No.', 'Unnamed: 1', 'Aceto Image Name', 'Vessel Image Name',
       ' Lugol Image Name', 'Unnamed: 5', 'Aceto Uptake', 'Margins', 'Vessels',
       'Lesion Size', 'Iodine Uptake', 'Unnamed: 11', 'Swede Score'],
      dtype='object')

In [15]:
df_img=df[[" Lugol Image Name","Iodine Uptake"]]
df_img

Lugol Image Name  Iodine Uptake
0                 NaN            NaN
1             2_5.jpg            2.0
2             3_3.jpg            2.0
3             4_5.jpg            2.0
4             5_4.jpg            2.0
..                ...            ...
386               NaN            NaN
387               NaN            NaN
388               NaN            NaN
389               NaN            NaN
390               NaN            NaN

[391 rows x 2 columns]

In [16]:
df_img=df_img.dropna()
df_img

Lugol Image Name  Iodine Uptake
1             2_5.jpg            2.0
2             3_3.jpg            2.0
3             4_5.jpg            2.0
4             5_4.jpg            2.0
5             6_4.jpg            2.0
..                ...            ...
358          AEH2.jpg            2.0
359          AAM2.jpg            2.0
367          ABX2.jpg            2.0
368          ADS2.jpg            2.0
370          APW2.jpg            2.0

[106 rows x 2 columns]

In [17]:
def update_img_name(img_name):
    return img_name.replace('.jpg', '_crop1.jpg')
df_img[' Lugol Image Name'] = df_img[' Lugol Image Name'].apply(update_img_name)

C:\Users\sakth\AppData\Local\Temp\ipykernel_19788\3501884195.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_img[' Lugol Image Name'] = df_img[' Lugol Image Name'].apply(update_img_name)


In [18]:
df_img

Lugol Image Name  Iodine Uptake
1       2_5_crop1.jpg            2.0
2       3_3_crop1.jpg            2.0
3       4_5_crop1.jpg            2.0
4       5_4_crop1.jpg            2.0
5       6_4_crop1.jpg            2.0
..                ...            ...
358    AEH2_crop1.jpg            2.0
359    AAM2_crop1.jpg            2.0
367    ABX2_crop1.jpg            2.0
368    ADS2_crop1.jpg            2.0
370    APW2_crop1.jpg            2.0

[106 rows x 2 columns]

In [20]:
df_img.rename(columns={" Lugol Image Name": "Image Name"},inplace=True)
df_img

C:\Users\sakth\AppData\Local\Temp\ipykernel_19788\1156118783.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_img.rename(columns={" Lugol Image Name": "Image Name"},inplace=True)


Image Name  Iodine Uptake
1     2_5_crop1.jpg            2.0
2     3_3_crop1.jpg            2.0
3     4_5_crop1.jpg            2.0
4     5_4_crop1.jpg            2.0
5     6_4_crop1.jpg            2.0
..              ...            ...
358  AEH2_crop1.jpg            2.0
359  AAM2_crop1.jpg            2.0
367  ABX2_crop1.jpg            2.0
368  ADS2_crop1.jpg            2.0
370  APW2_crop1.jpg            2.0

[106 rows x 2 columns]

In [21]:
glcm= pd.read_excel('glcm_c.xlsx')
glcm

Image Name    Contrast  Dissimilarity  Homogeneity    Energy  \
0     12_5_crop1.jpg  157.854147       4.624647     0.573563  0.442468   
1     14_8_crop1.jpg  155.483755       5.115023     0.529159  0.439409   
2     15_3_crop1.jpg   68.943292       2.706758     0.623281  0.438376   
3     16_5_crop1.jpg  256.131569       6.521085     0.537425  0.440008   
4    173_2_crop1.jpg   75.916357       2.870332     0.592028  0.306839   
..               ...         ...            ...          ...       ...   
101   AEN2_crop1.jpg   36.827210       1.848549     0.701685  0.576838   
102   AEO2_crop1.jpg  205.624812       4.511653     0.687164  0.583636   
103   AEP2_crop1.jpg  216.407899       4.567397     0.668367  0.581761   
104   AES2_crop1.jpg  117.430474       3.008281     0.688336  0.576258   
105   AFB2_crop1.jpg  118.291082       3.005935     0.685966  0.574594   

     Correlation   Entropy  
0       0.980000  5.147902  
1       0.983700  5.182583  
2       0.993289  5.322754  
3       0.977944  5.324595  
4       0.977619  5.472964  
..           ...       ...  
101     0.994538  4.110047  
102     0.976044  4.168433  
103     0.976316  4.164413  
104     0.987764  4.021915  
105     0.992291  3.995815  

[106 rows x 7 columns]

In [22]:
final=pd.merge(glcm, df_img, on='Image Name')
final

Image Name    Contrast  Dissimilarity  Homogeneity    Energy  \
0     12_5_crop1.jpg  157.854147       4.624647     0.573563  0.442468   
1     14_8_crop1.jpg  155.483755       5.115023     0.529159  0.439409   
2     15_3_crop1.jpg   68.943292       2.706758     0.623281  0.438376   
3     16_5_crop1.jpg  256.131569       6.521085     0.537425  0.440008   
4    173_2_crop1.jpg   75.916357       2.870332     0.592028  0.306839   
..               ...         ...            ...          ...       ...   
98    AEN2_crop1.jpg   36.827210       1.848549     0.701685  0.576838   
99    AEO2_crop1.jpg  205.624812       4.511653     0.687164  0.583636   
100   AEP2_crop1.jpg  216.407899       4.567397     0.668367  0.581761   
101   AES2_crop1.jpg  117.430474       3.008281     0.688336  0.576258   
102   AFB2_crop1.jpg  118.291082       3.005935     0.685966  0.574594   

     Correlation   Entropy  Iodine Uptake  
0       0.980000  5.147902            2.0  
1       0.983700  5.182583            2.0  
2       0.993289  5.322754            2.0  
3       0.977944  5.324595            2.0  
4       0.977619  5.472964            1.0  
..           ...       ...            ...  
98      0.994538  4.110047            2.0  
99      0.976044  4.168433            2.0  
100     0.976316  4.164413            0.0  
101     0.987764  4.021915            2.0  
102     0.992291  3.995815            2.0  

[103 rows x 8 columns]

In [23]:
X=final.iloc[:,1:7]
X.head()


Contrast  Dissimilarity  Homogeneity    Energy  Correlation   Entropy
0  157.854147       4.624647     0.573563  0.442468     0.980000  5.147902
1  155.483755       5.115023     0.529159  0.439409     0.983700  5.182583
2   68.943292       2.706758     0.623281  0.438376     0.993289  5.322754
3  256.131569       6.521085     0.537425  0.440008     0.977944  5.324595
4   75.916357       2.870332     0.592028  0.306839     0.977619  5.472964

In [25]:

Y=final["Iodine Uptake"]
Y.head()


0    2.0
1    2.0
2    2.0
3    2.0
4    1.0
Name: Iodine Uptake, dtype: float64

In [26]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test= train_test_split(X,Y, random_state=100, test_size=0.2)
y_train.head()

import time
from sklearn.svm import SVC 
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
svm = SVC(kernel = 'linear', C = 1)
svm.fit(x_train, y_train) 
start=time.time()
svm_predictions = svm.predict(x_test) 
# model accuracy for X_test   
accuracy = svm.score(x_test, y_test)

# creating a confusion matrix 
cm = confusion_matrix(y_test, svm_predictions) 
print("Accuracy of SVM is:",accuracy)
end=time.time()
print("Time taken:", end - start) 
print(cm)


Accuracy of SVM is: 0.7142857142857143
Time taken: 0.009092330932617188
[[ 0  0  5]
 [ 0  0  1]
 [ 0  0 15]]


In [27]:

from sklearn.ensemble import RandomForestClassifier
model=RandomForestClassifier(n_estimators=25)
model.fit(x_train,y_train)
preds=model.predict(x_test)
acc=accuracy_score(y_test,preds)
print("The Accuracy of randomforestclassifier is:", acc)

parameters = {
    "n_estimators":[5,10,50,100,250],
    "max_depth":[2,4,8,16,32,None]
}

from sklearn.model_selection import GridSearchCV
cv = GridSearchCV(model,parameters,cv=5)
start=time.time()
cv.fit(x_train,y_train)
end=time.time()
print("The best accuracy score obtained is:",cv.best_score_," at parameters ", cv.best_params_)
print("Time taken:", end-start)


The Accuracy of randomforestclassifier is: 0.6190476190476191


c:\Users\sakth\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\model_selection\_split.py:725: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(


The best accuracy score obtained is: 0.7051470588235293  at parameters  {'max_depth': None, 'n_estimators': 5}
Time taken: 29.219440460205078


In [28]:


from sklearn.ensemble import RandomForestClassifier
model=RandomForestClassifier(n_estimators=50)
model.fit(x_train,y_train)
preds=model.predict(x_test)
acc=accuracy_score(y_test,preds)
print("The Accuracy of randomforestclassifier is:", acc)
cm = confusion_matrix(y_test, preds) 
print(cm)


The Accuracy of randomforestclassifier is: 0.8095238095238095
[[ 2  0  3]
 [ 0  0  1]
 [ 0  0 15]]


In [29]:

from sklearn.ensemble import GradientBoostingClassifier

model= GradientBoostingClassifier()
start=time.time()
model.fit(x_train,y_train)
end=time.time()
preds=model.predict(x_test)
acc=accuracy_score(y_test, preds)
print("Accuracy:", acc)
print("Time taken:", end-start)
cm = confusion_matrix(y_test, preds) 
print(cm)


Accuracy: 0.6666666666666666
Time taken: 0.7120575904846191
[[ 1  0  4]
 [ 0  0  1]
 [ 2  0 13]]


In [30]:

from sklearn.naive_bayes import GaussianNB
model=GaussianNB()
start=time.time()
model.fit(x_train,y_train)
end=time.time()
preds=model.predict(x_test)
acc=accuracy_score(y_test,preds)
print("The Accuracy of Naive Bayes is:", acc)
print("Time:", end-start)
cm = confusion_matrix(y_test, preds) 
print(cm)


The Accuracy of Naive Bayes is: 0.5714285714285714
Time: 0.004030466079711914
[[4 0 1]
 [0 0 1]
 [7 0 8]]


In [31]:

from sklearn.linear_model import LogisticRegression
model=LogisticRegression()
start=time.time()
model.fit(x_train,y_train)
end=time.time()
preds=model.predict(x_test)
acc=accuracy_score(y_test,preds)
print("The Accuracy of Logistic regression is:", acc)
print("Time:", end-start)
cm = confusion_matrix(y_test, preds) 
print(cm)


The Accuracy of Logistic regression is: 0.5238095238095238
Time: 0.07090330123901367
[[ 0  0  5]
 [ 0  0  1]
 [ 4  0 11]]


c:\Users\sakth\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [33]:

final=final[final["Iodine Uptake"]!=1.0]
final


Image Name    Contrast  Dissimilarity  Homogeneity    Energy  \
0     12_5_crop1.jpg  157.854147       4.624647     0.573563  0.442468   
1     14_8_crop1.jpg  155.483755       5.115023     0.529159  0.439409   
2     15_3_crop1.jpg   68.943292       2.706758     0.623281  0.438376   
3     16_5_crop1.jpg  256.131569       6.521085     0.537425  0.440008   
7    176_2_crop1.jpg  176.402588       5.438185     0.458793  0.301494   
..               ...         ...            ...          ...       ...   
98    AEN2_crop1.jpg   36.827210       1.848549     0.701685  0.576838   
99    AEO2_crop1.jpg  205.624812       4.511653     0.687164  0.583636   
100   AEP2_crop1.jpg  216.407899       4.567397     0.668367  0.581761   
101   AES2_crop1.jpg  117.430474       3.008281     0.688336  0.576258   
102   AFB2_crop1.jpg  118.291082       3.005935     0.685966  0.574594   

     Correlation   Entropy  Iodine Uptake  
0       0.980000  5.147902            2.0  
1       0.983700  5.182583            2.0  
2       0.993289  5.322754            2.0  
3       0.977944  5.324595            2.0  
7       0.967304  6.000161            2.0  
..           ...       ...            ...  
98      0.994538  4.110047            2.0  
99      0.976044  4.168433            2.0  
100     0.976316  4.164413            0.0  
101     0.987764  4.021915            2.0  
102     0.992291  3.995815            2.0  

[98 rows x 8 columns]

In [34]:


X=final.iloc[:,1:7]
X.head()


Contrast  Dissimilarity  Homogeneity    Energy  Correlation   Entropy
0  157.854147       4.624647     0.573563  0.442468     0.980000  5.147902
1  155.483755       5.115023     0.529159  0.439409     0.983700  5.182583
2   68.943292       2.706758     0.623281  0.438376     0.993289  5.322754
3  256.131569       6.521085     0.537425  0.440008     0.977944  5.324595
7  176.402588       5.438185     0.458793  0.301494     0.967304  6.000161

In [36]:


Y=final["Iodine Uptake"]
Y.head()



0    2.0
1    2.0
2    2.0
3    2.0
7    2.0
Name: Iodine Uptake, dtype: float64

In [37]:


from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test= train_test_split(X,Y, random_state=100, test_size=0.2)
y_train.head()




25    2.0
28    2.0
10    2.0
3     2.0
45    0.0
Name: Iodine Uptake, dtype: float64

In [38]:

import time
from sklearn.svm import SVC 
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
svm = SVC(kernel = 'linear', C = 1)
svm.fit(x_train, y_train) 
start=time.time()
svm_predictions = svm.predict(x_test) 
# model accuracy for X_test   
accuracy = svm.score(x_test, y_test)

# creating a confusion matrix 
cm = confusion_matrix(y_test, svm_predictions) 
print("Accuracy of SVM is:",accuracy)
end=time.time()
print("Time taken:", end - start) 
print(cm)



Accuracy of SVM is: 0.85
Time taken: 0.0051763057708740234
[[ 0  3]
 [ 0 17]]


In [39]:


from sklearn.ensemble import RandomForestClassifier
model=RandomForestClassifier(n_estimators=25)
model.fit(x_train,y_train)
preds=model.predict(x_test)
acc=accuracy_score(y_test,preds)
print("The Accuracy of randomforestclassifier is:", acc)

parameters = {
    "n_estimators":[5,10,50,100,250],
    "max_depth":[2,4,8,16,32,None]
}

from sklearn.model_selection import GridSearchCV
cv = GridSearchCV(model,parameters,cv=5)
start=time.time()
cv.fit(x_train,y_train)
end=time.time()
print("The best accuracy score obtained is:",cv.best_score_," at parameters ", cv.best_params_)
print("Time taken:", end-start)



The Accuracy of randomforestclassifier is: 0.75
The best accuracy score obtained is: 0.7283333333333333  at parameters  {'max_depth': 8, 'n_estimators': 5}
Time taken: 25.91698980331421


In [40]:


from sklearn.ensemble import RandomForestClassifier
model=RandomForestClassifier(n_estimators=50, max_depth=16)
model.fit(x_train,y_train)
preds=model.predict(x_test)
acc=accuracy_score(y_test,preds)
print("The Accuracy of randomforestclassifier is:", acc)
cm = confusion_matrix(y_test, preds) 
print(cm)



The Accuracy of randomforestclassifier is: 0.75
[[ 1  2]
 [ 3 14]]


In [41]:


from sklearn.ensemble import GradientBoostingClassifier

model= GradientBoostingClassifier()
start=time.time()
model.fit(x_train,y_train)
end=time.time()
preds=model.predict(x_test)
acc=accuracy_score(y_test, preds)
print("Accuracy:", acc)
print("Time taken:", end-start)
cm = confusion_matrix(y_test, preds) 
print(cm)




Accuracy: 0.8
Time taken: 0.20388078689575195
[[ 1  2]
 [ 2 15]]


In [42]:

from sklearn.naive_bayes import GaussianNB
model=GaussianNB()
start=time.time()
model.fit(x_train,y_train)
end=time.time()
preds=model.predict(x_test)
acc=accuracy_score(y_test,preds)
print("The Accuracy of Naive Bayes is:", acc)
print("Time:", end-start)
cm = confusion_matrix(y_test, preds) 
print(cm)



The Accuracy of Naive Bayes is: 0.75
Time: 0.004004001617431641
[[ 3  0]
 [ 5 12]]


In [43]:


from sklearn.linear_model import LogisticRegression
model=LogisticRegression()
start=time.time()
model.fit(x_train,y_train)
end=time.time()
preds=model.predict(x_test)
acc=accuracy_score(y_test,preds)
print("The Accuracy of Logistic regression is:", acc)
print("Time:", end-start)
cm = confusion_matrix(y_test, preds) 
print(cm)

The Accuracy of Logistic regression is: 0.85
Time: 0.030488967895507812
[[ 0  3]
 [ 0 17]]
