In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_excel('Labelled_DATA(1).xlsx')
df

Case No. Unnamed: 1 Aceto Image Name      Vessel Image Name  \
0           1        NaN              NaN                    NaN   
1           2        NaN              NaN  2.1_2.jpg , 2.2_4.jpg   
2           3        NaN              NaN                    NaN   
3           4        NaN              NaN              4.2_4.jpg   
4           5        NaN              NaN              5.1_1.jpg   
..        ...        ...              ...                    ...   
386       387        AAR         AAR1.jpg                    NaN   
387       388        AEY         AEY1.jpg                    NaN   
388       389        AEU         AEU1.jpg                    NaN   
389       390        ADF         ADF1.jpg                    NaN   
390       391        ABK         ABK1.jpg                    NaN   

     Lugol Image Name  Unnamed: 5  Aceto Uptake  Margins  Vessels  \
0                 NaN         NaN           2.0      NaN      NaN   
1             2_5.jpg         NaN           2.0      2.0      1.0   
2             3_3.jpg         NaN           2.0      NaN      NaN   
3             4_5.jpg         NaN           2.0      NaN      2.0   
4             5_4.jpg         NaN           2.0      NaN      1.0   
..                ...         ...           ...      ...      ...   
386               NaN         NaN           2.0      NaN      NaN   
387               NaN         NaN           2.0      NaN      NaN   
388               NaN         NaN           2.0      NaN      NaN   
389               NaN         NaN           2.0      NaN      NaN   
390               NaN         NaN           2.0      NaN      NaN   

     Lesion Size  Iodine Uptake  Unnamed: 11  Swede Score  
0            NaN            NaN          NaN          NaN  
1            1.0            2.0          NaN          8.0  
2            NaN            2.0          NaN          9.0  
3            NaN            2.0          NaN         10.0  
4            NaN            2.0          NaN          9.0  
..           ...            ...          ...          ...  
386          NaN            NaN          NaN          NaN  
387          NaN            NaN          NaN          NaN  
388          NaN            NaN          NaN          NaN  
389          NaN            NaN          NaN          NaN  
390          NaN            NaN          NaN          NaN  

[391 rows x 13 columns]

In [3]:
df.columns

Index(['Case No.', 'Unnamed: 1', 'Aceto Image Name', 'Vessel Image Name',
       ' Lugol Image Name', 'Unnamed: 5', 'Aceto Uptake', 'Margins', 'Vessels',
       'Lesion Size', 'Iodine Uptake', 'Unnamed: 11', 'Swede Score'],
      dtype='object')

In [4]:
df_img=df[[" Lugol Image Name","Iodine Uptake"]]
df_img

Lugol Image Name  Iodine Uptake
0                 NaN            NaN
1             2_5.jpg            2.0
2             3_3.jpg            2.0
3             4_5.jpg            2.0
4             5_4.jpg            2.0
..                ...            ...
386               NaN            NaN
387               NaN            NaN
388               NaN            NaN
389               NaN            NaN
390               NaN            NaN

[391 rows x 2 columns]

In [5]:
df_img=df_img.dropna()
df_img

Lugol Image Name  Iodine Uptake
1             2_5.jpg            2.0
2             3_3.jpg            2.0
3             4_5.jpg            2.0
4             5_4.jpg            2.0
5             6_4.jpg            2.0
..                ...            ...
358          AEH2.jpg            2.0
359          AAM2.jpg            2.0
367          ABX2.jpg            2.0
368          ADS2.jpg            2.0
370          APW2.jpg            2.0

[106 rows x 2 columns]

In [6]:
def update_img_name(img_name):
    return img_name.replace('.jpg', '_in.jpg')
df_img[' Lugol Image Name'] = df_img[' Lugol Image Name'].apply(update_img_name)

C:\Users\sakth\AppData\Local\Temp\ipykernel_13320\2016604649.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_img[' Lugol Image Name'] = df_img[' Lugol Image Name'].apply(update_img_name)


In [7]:
df_img

Lugol Image Name  Iodine Uptake
1          2_5_in.jpg            2.0
2          3_3_in.jpg            2.0
3          4_5_in.jpg            2.0
4          5_4_in.jpg            2.0
5          6_4_in.jpg            2.0
..                ...            ...
358       AEH2_in.jpg            2.0
359       AAM2_in.jpg            2.0
367       ABX2_in.jpg            2.0
368       ADS2_in.jpg            2.0
370       APW2_in.jpg            2.0

[106 rows x 2 columns]

In [8]:
df_img.rename(columns={" Lugol Image Name": "Image Name"},inplace=True)
df_img

C:\Users\sakth\AppData\Local\Temp\ipykernel_13320\1156118783.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_img.rename(columns={" Lugol Image Name": "Image Name"},inplace=True)


Image Name  Iodine Uptake
1     2_5_in.jpg            2.0
2     3_3_in.jpg            2.0
3     4_5_in.jpg            2.0
4     5_4_in.jpg            2.0
5     6_4_in.jpg            2.0
..           ...            ...
358  AEH2_in.jpg            2.0
359  AAM2_in.jpg            2.0
367  ABX2_in.jpg            2.0
368  ADS2_in.jpg            2.0
370  APW2_in.jpg            2.0

[106 rows x 2 columns]

In [9]:
glcm= pd.read_excel('glcm_in.xlsx')
glcm

Image Name   Contrast  Dissimilarity  Homogeneity    Energy  \
0     12_5_in.jpg  72.350029       4.103312     0.341656  0.030235   
1     14_8_in.jpg  60.837904       4.467987     0.309507  0.020635   
2     15_3_in.jpg  28.833995       2.742772     0.424017  0.026834   
3     16_5_in.jpg  61.335847       4.168296     0.377720  0.024385   
4    173_2_in.jpg  20.680816       2.443358     0.438396  0.079955   
..            ...        ...            ...          ...       ...   
101   AEN2_in.jpg  26.713188       3.033916     0.365819  0.024039   
102   AEO2_in.jpg  66.919996       3.888861     0.432284  0.032348   
103   AEP2_in.jpg  75.535070       4.267734     0.327208  0.020371   
104   AES2_in.jpg  91.241943       4.088299     0.351814  0.026878   
105   AFB2_in.jpg  74.171927       4.239051     0.317520  0.022157   

     Correlation   Entropy  
0       0.991623  7.730848  
1       0.990420  7.657443  
2       0.995917  7.720428  
3       0.991272  7.699633  
4       0.993018  6.692333  
..           ...       ...  
101     0.997204  7.794836  
102     0.992671  7.820010  
103     0.986839  7.685473  
104     0.983413  7.413617  
105     0.987630  7.594580  

[106 rows x 7 columns]

In [10]:
final=pd.merge(glcm, df_img, on='Image Name')
final

Image Name   Contrast  Dissimilarity  Homogeneity    Energy  \
0     12_5_in.jpg  72.350029       4.103312     0.341656  0.030235   
1     14_8_in.jpg  60.837904       4.467987     0.309507  0.020635   
2     15_3_in.jpg  28.833995       2.742772     0.424017  0.026834   
3     16_5_in.jpg  61.335847       4.168296     0.377720  0.024385   
4    173_2_in.jpg  20.680816       2.443358     0.438396  0.079955   
..            ...        ...            ...          ...       ...   
98    AEN2_in.jpg  26.713188       3.033916     0.365819  0.024039   
99    AEO2_in.jpg  66.919996       3.888861     0.432284  0.032348   
100   AEP2_in.jpg  75.535070       4.267734     0.327208  0.020371   
101   AES2_in.jpg  91.241943       4.088299     0.351814  0.026878   
102   AFB2_in.jpg  74.171927       4.239051     0.317520  0.022157   

     Correlation   Entropy  Iodine Uptake  
0       0.991623  7.730848            2.0  
1       0.990420  7.657443            2.0  
2       0.995917  7.720428            2.0  
3       0.991272  7.699633            2.0  
4       0.993018  6.692333            1.0  
..           ...       ...            ...  
98      0.997204  7.794836            2.0  
99      0.992671  7.820010            2.0  
100     0.986839  7.685473            0.0  
101     0.983413  7.413617            2.0  
102     0.987630  7.594580            2.0  

[103 rows x 8 columns]

In [11]:
X=final.iloc[:,1:7]
X.head()


Contrast  Dissimilarity  Homogeneity    Energy  Correlation   Entropy
0  72.350029       4.103312     0.341656  0.030235     0.991623  7.730848
1  60.837904       4.467987     0.309507  0.020635     0.990420  7.657443
2  28.833995       2.742772     0.424017  0.026834     0.995917  7.720428
3  61.335847       4.168296     0.377720  0.024385     0.991272  7.699633
4  20.680816       2.443358     0.438396  0.079955     0.993018  6.692333

In [12]:

Y=final["Iodine Uptake"]
Y.head()


0    2.0
1    2.0
2    2.0
3    2.0
4    1.0
Name: Iodine Uptake, dtype: float64

In [13]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test= train_test_split(X,Y, random_state=100, test_size=0.2)
y_train.head()

import time
from sklearn.svm import SVC 
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
svm = SVC(kernel = 'linear', C = 1)
svm.fit(x_train, y_train) 
start=time.time()
svm_predictions = svm.predict(x_test) 
# model accuracy for X_test   
accuracy = svm.score(x_test, y_test)

# creating a confusion matrix 
cm = confusion_matrix(y_test, svm_predictions) 
print("Accuracy of SVM is:",accuracy)
end=time.time()
print("Time taken:", end - start) 
print(cm)


Accuracy of SVM is: 0.7142857142857143
Time taken: 0.007623434066772461
[[ 0  0  5]
 [ 0  0  1]
 [ 0  0 15]]


In [14]:

from sklearn.ensemble import RandomForestClassifier
model=RandomForestClassifier(n_estimators=25)
model.fit(x_train,y_train)
preds=model.predict(x_test)
acc=accuracy_score(y_test,preds)
print("The Accuracy of randomforestclassifier is:", acc)

parameters = {
    "n_estimators":[5,10,50,100,250],
    "max_depth":[2,4,8,16,32,None]
}

from sklearn.model_selection import GridSearchCV
cv = GridSearchCV(model,parameters,cv=5)
start=time.time()
cv.fit(x_train,y_train)
end=time.time()
print("The best accuracy score obtained is:",cv.best_score_," at parameters ", cv.best_params_)
print("Time taken:", end-start)


The Accuracy of randomforestclassifier is: 0.7142857142857143


c:\Users\sakth\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\model_selection\_split.py:725: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(


The best accuracy score obtained is: 0.7566176470588235  at parameters  {'max_depth': 2, 'n_estimators': 5}
Time taken: 33.03140211105347


In [15]:


from sklearn.ensemble import RandomForestClassifier
model=RandomForestClassifier(n_estimators=50)
model.fit(x_train,y_train)
preds=model.predict(x_test)
acc=accuracy_score(y_test,preds)
print("The Accuracy of randomforestclassifier is:", acc)
cm = confusion_matrix(y_test, preds) 
print(cm)


The Accuracy of randomforestclassifier is: 0.7142857142857143
[[ 2  0  3]
 [ 0  0  1]
 [ 2  0 13]]


In [16]:

from sklearn.ensemble import GradientBoostingClassifier

model= GradientBoostingClassifier()
start=time.time()
model.fit(x_train,y_train)
end=time.time()
preds=model.predict(x_test)
acc=accuracy_score(y_test, preds)
print("Accuracy:", acc)
print("Time taken:", end-start)
cm = confusion_matrix(y_test, preds) 
print(cm)


Accuracy: 0.7142857142857143
Time taken: 0.7386469841003418
[[ 2  0  3]
 [ 0  1  0]
 [ 2  1 12]]


In [17]:

from sklearn.naive_bayes import GaussianNB
model=GaussianNB()
start=time.time()
model.fit(x_train,y_train)
end=time.time()
preds=model.predict(x_test)
acc=accuracy_score(y_test,preds)
print("The Accuracy of Naive Bayes is:", acc)
print("Time:", end-start)
cm = confusion_matrix(y_test, preds) 
print(cm)


The Accuracy of Naive Bayes is: 0.5238095238095238
Time: 0.00600743293762207
[[4 0 1]
 [0 0 1]
 [5 3 7]]


In [18]:

from sklearn.linear_model import LogisticRegression
model=LogisticRegression()
start=time.time()
model.fit(x_train,y_train)
end=time.time()
preds=model.predict(x_test)
acc=accuracy_score(y_test,preds)
print("The Accuracy of Logistic regression is:", acc)
print("Time:", end-start)
cm = confusion_matrix(y_test, preds) 
print(cm)


The Accuracy of Logistic regression is: 0.6190476190476191
Time: 0.06092500686645508
[[ 0  0  5]
 [ 0  0  1]
 [ 0  2 13]]


c:\Users\sakth\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [19]:

final=final[final["Iodine Uptake"]!=1.0]
final


Image Name   Contrast  Dissimilarity  Homogeneity    Energy  \
0     12_5_in.jpg  72.350029       4.103312     0.341656  0.030235   
1     14_8_in.jpg  60.837904       4.467987     0.309507  0.020635   
2     15_3_in.jpg  28.833995       2.742772     0.424017  0.026834   
3     16_5_in.jpg  61.335847       4.168296     0.377720  0.024385   
7    176_2_in.jpg  76.682292       5.255936     0.258950  0.030958   
..            ...        ...            ...          ...       ...   
98    AEN2_in.jpg  26.713188       3.033916     0.365819  0.024039   
99    AEO2_in.jpg  66.919996       3.888861     0.432284  0.032348   
100   AEP2_in.jpg  75.535070       4.267734     0.327208  0.020371   
101   AES2_in.jpg  91.241943       4.088299     0.351814  0.026878   
102   AFB2_in.jpg  74.171927       4.239051     0.317520  0.022157   

     Correlation   Entropy  Iodine Uptake  
0       0.991623  7.730848            2.0  
1       0.990420  7.657443            2.0  
2       0.995917  7.720428            2.0  
3       0.991272  7.699633            2.0  
7       0.984442  7.356312            2.0  
..           ...       ...            ...  
98      0.997204  7.794836            2.0  
99      0.992671  7.820010            2.0  
100     0.986839  7.685473            0.0  
101     0.983413  7.413617            2.0  
102     0.987630  7.594580            2.0  

[98 rows x 8 columns]

In [20]:


X=final.iloc[:,1:7]
X.head()


Contrast  Dissimilarity  Homogeneity    Energy  Correlation   Entropy
0  72.350029       4.103312     0.341656  0.030235     0.991623  7.730848
1  60.837904       4.467987     0.309507  0.020635     0.990420  7.657443
2  28.833995       2.742772     0.424017  0.026834     0.995917  7.720428
3  61.335847       4.168296     0.377720  0.024385     0.991272  7.699633
7  76.682292       5.255936     0.258950  0.030958     0.984442  7.356312

In [21]:


Y=final["Iodine Uptake"]
Y.head()



0    2.0
1    2.0
2    2.0
3    2.0
7    2.0
Name: Iodine Uptake, dtype: float64

In [22]:


from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test= train_test_split(X,Y, random_state=100, test_size=0.2)
y_train.head()




25    2.0
28    2.0
10    2.0
3     2.0
45    0.0
Name: Iodine Uptake, dtype: float64

In [23]:

import time
from sklearn.svm import SVC 
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
svm = SVC(kernel = 'linear', C = 1)
svm.fit(x_train, y_train) 
start=time.time()
svm_predictions = svm.predict(x_test) 
# model accuracy for X_test   
accuracy = svm.score(x_test, y_test)

# creating a confusion matrix 
cm = confusion_matrix(y_test, svm_predictions) 
print("Accuracy of SVM is:",accuracy)
end=time.time()
print("Time taken:", end - start) 
print(cm)



Accuracy of SVM is: 0.85
Time taken: 0.01636362075805664
[[ 0  3]
 [ 0 17]]


In [24]:


from sklearn.ensemble import RandomForestClassifier
model=RandomForestClassifier(n_estimators=25)
model.fit(x_train,y_train)
preds=model.predict(x_test)
acc=accuracy_score(y_test,preds)
print("The Accuracy of randomforestclassifier is:", acc)

parameters = {
    "n_estimators":[5,10,50,100,250],
    "max_depth":[2,4,8,16,32,None]
}

from sklearn.model_selection import GridSearchCV
cv = GridSearchCV(model,parameters,cv=5)
start=time.time()
cv.fit(x_train,y_train)
end=time.time()
print("The best accuracy score obtained is:",cv.best_score_," at parameters ", cv.best_params_)
print("Time taken:", end-start)



The Accuracy of randomforestclassifier is: 0.85
The best accuracy score obtained is: 0.7424999999999999  at parameters  {'max_depth': 4, 'n_estimators': 100}
Time taken: 27.327927589416504


In [25]:


from sklearn.ensemble import RandomForestClassifier
model=RandomForestClassifier(n_estimators=50, max_depth=16)
model.fit(x_train,y_train)
preds=model.predict(x_test)
acc=accuracy_score(y_test,preds)
print("The Accuracy of randomforestclassifier is:", acc)
cm = confusion_matrix(y_test, preds) 
print(cm)



The Accuracy of randomforestclassifier is: 0.8
[[ 1  2]
 [ 2 15]]


In [26]:


from sklearn.ensemble import GradientBoostingClassifier

model= GradientBoostingClassifier()
start=time.time()
model.fit(x_train,y_train)
end=time.time()
preds=model.predict(x_test)
acc=accuracy_score(y_test, preds)
print("Accuracy:", acc)
print("Time taken:", end-start)
cm = confusion_matrix(y_test, preds) 
print(cm)




Accuracy: 0.85
Time taken: 0.19180917739868164
[[ 2  1]
 [ 2 15]]


In [27]:

from sklearn.naive_bayes import GaussianNB
model=GaussianNB()
start=time.time()
model.fit(x_train,y_train)
end=time.time()
preds=model.predict(x_test)
acc=accuracy_score(y_test,preds)
print("The Accuracy of Naive Bayes is:", acc)
print("Time:", end-start)
cm = confusion_matrix(y_test, preds) 
print(cm)



The Accuracy of Naive Bayes is: 0.55
Time: 0.0040187835693359375
[[3 0]
 [9 8]]


In [28]:


from sklearn.linear_model import LogisticRegression
model=LogisticRegression()
start=time.time()
model.fit(x_train,y_train)
end=time.time()
preds=model.predict(x_test)
acc=accuracy_score(y_test,preds)
print("The Accuracy of Logistic regression is:", acc)
print("Time:", end-start)
cm = confusion_matrix(y_test, preds) 
print(cm)

The Accuracy of Logistic regression is: 0.8
Time: 0.03214240074157715
[[ 0  3]
 [ 1 16]]
