In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_excel('Labelled_DATA(1).xlsx')
df

Case No. Unnamed: 1 Aceto Image Name      Vessel Image Name  \
0           1        NaN              NaN                    NaN   
1           2        NaN              NaN  2.1_2.jpg , 2.2_4.jpg   
2           3        NaN              NaN                    NaN   
3           4        NaN              NaN              4.2_4.jpg   
4           5        NaN              NaN              5.1_1.jpg   
..        ...        ...              ...                    ...   
386       387        AAR         AAR1.jpg                    NaN   
387       388        AEY         AEY1.jpg                    NaN   
388       389        AEU         AEU1.jpg                    NaN   
389       390        ADF         ADF1.jpg                    NaN   
390       391        ABK         ABK1.jpg                    NaN   

     Lugol Image Name  Unnamed: 5  Aceto Uptake  Margins  Vessels  \
0                 NaN         NaN           2.0      NaN      NaN   
1             2_5.jpg         NaN           2.0      2.0      1.0   
2             3_3.jpg         NaN           2.0      NaN      NaN   
3             4_5.jpg         NaN           2.0      NaN      2.0   
4             5_4.jpg         NaN           2.0      NaN      1.0   
..                ...         ...           ...      ...      ...   
386               NaN         NaN           2.0      NaN      NaN   
387               NaN         NaN           2.0      NaN      NaN   
388               NaN         NaN           2.0      NaN      NaN   
389               NaN         NaN           2.0      NaN      NaN   
390               NaN         NaN           2.0      NaN      NaN   

     Lesion Size  Iodine Uptake  Unnamed: 11  Swede Score  
0            NaN            NaN          NaN          NaN  
1            1.0            2.0          NaN          8.0  
2            NaN            2.0          NaN          9.0  
3            NaN            2.0          NaN         10.0  
4            NaN            2.0          NaN          9.0  
..           ...            ...          ...          ...  
386          NaN            NaN          NaN          NaN  
387          NaN            NaN          NaN          NaN  
388          NaN            NaN          NaN          NaN  
389          NaN            NaN          NaN          NaN  
390          NaN            NaN          NaN          NaN  

[391 rows x 13 columns]

In [3]:
df=df.iloc[45:390, :]
df

Case No. Unnamed: 1 Aceto Image Name Vessel Image Name  Lugol Image Name  \
45         46        NaN           46.jpg               NaN               NaN   
46         47        NaN           47.jpg               NaN               NaN   
47         48        NaN           48.jpg               NaN               NaN   
48         49        NaN           49.jpg               NaN               NaN   
49         50        NaN           50.jpg               NaN               NaN   
..        ...        ...              ...               ...               ...   
385       386        AAC         AAC1.jpg               NaN               NaN   
386       387        AAR         AAR1.jpg               NaN               NaN   
387       388        AEY         AEY1.jpg               NaN               NaN   
388       389        AEU         AEU1.jpg               NaN               NaN   
389       390        ADF         ADF1.jpg               NaN               NaN   

     Unnamed: 5  Aceto Uptake  Margins  Vessels  Lesion Size  Iodine Uptake  \
45          NaN           0.0      NaN      NaN          NaN            NaN   
46          NaN           0.0      NaN      NaN          NaN            NaN   
47          NaN           0.0      NaN      NaN          NaN            NaN   
48          NaN           0.0      NaN      NaN          NaN            NaN   
49          NaN           0.0      NaN      NaN          NaN            NaN   
..          ...           ...      ...      ...          ...            ...   
385         NaN           2.0      NaN      NaN          NaN            NaN   
386         NaN           2.0      NaN      NaN          NaN            NaN   
387         NaN           2.0      NaN      NaN          NaN            NaN   
388         NaN           2.0      NaN      NaN          NaN            NaN   
389         NaN           2.0      NaN      NaN          NaN            NaN   

     Unnamed: 11  Swede Score  
45           NaN          NaN  
46           NaN          NaN  
47           NaN          NaN  
48           NaN          NaN  
49           NaN          NaN  
..           ...          ...  
385          NaN          NaN  
386          NaN          NaN  
387          NaN          NaN  
388          NaN          NaN  
389          NaN          NaN  

[345 rows x 13 columns]

In [4]:
df_img=df[["Aceto Image Name","Aceto Uptake"]]
df_img

Aceto Image Name  Aceto Uptake
45            46.jpg           0.0
46            47.jpg           0.0
47            48.jpg           0.0
48            49.jpg           0.0
49            50.jpg           0.0
..               ...           ...
385         AAC1.jpg           2.0
386         AAR1.jpg           2.0
387         AEY1.jpg           2.0
388         AEU1.jpg           2.0
389         ADF1.jpg           2.0

[345 rows x 2 columns]

In [5]:
df_img=df_img.dropna()
df_img

Aceto Image Name  Aceto Uptake
45            46.jpg           0.0
46            47.jpg           0.0
47            48.jpg           0.0
48            49.jpg           0.0
49            50.jpg           0.0
..               ...           ...
385         AAC1.jpg           2.0
386         AAR1.jpg           2.0
387         AEY1.jpg           2.0
388         AEU1.jpg           2.0
389         ADF1.jpg           2.0

[322 rows x 2 columns]

In [6]:
def update_img_name(img_name):
    return img_name.replace('.jpg', '_in.jpg')
df_img['Aceto Image Name'] = df_img['Aceto Image Name'].apply(update_img_name)

C:\Users\sakth\AppData\Local\Temp\ipykernel_12620\3233917316.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_img['Aceto Image Name'] = df_img['Aceto Image Name'].apply(update_img_name)


In [7]:
df_img

Aceto Image Name  Aceto Uptake
45         46_in.jpg           0.0
46         47_in.jpg           0.0
47         48_in.jpg           0.0
48         49_in.jpg           0.0
49         50_in.jpg           0.0
..               ...           ...
385      AAC1_in.jpg           2.0
386      AAR1_in.jpg           2.0
387      AEY1_in.jpg           2.0
388      AEU1_in.jpg           2.0
389      ADF1_in.jpg           2.0

[322 rows x 2 columns]

In [8]:
df_img.rename(columns={"Aceto Image Name": "Image Name"},inplace=True)
df_img

C:\Users\sakth\AppData\Local\Temp\ipykernel_12620\835848021.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_img.rename(columns={"Aceto Image Name": "Image Name"},inplace=True)


Image Name  Aceto Uptake
45     46_in.jpg           0.0
46     47_in.jpg           0.0
47     48_in.jpg           0.0
48     49_in.jpg           0.0
49     50_in.jpg           0.0
..           ...           ...
385  AAC1_in.jpg           2.0
386  AAR1_in.jpg           2.0
387  AEY1_in.jpg           2.0
388  AEU1_in.jpg           2.0
389  ADF1_in.jpg           2.0

[322 rows x 2 columns]

In [9]:
glcm= pd.read_excel('glcm_in.xlsx')
glcm

Image Name   Contrast  Dissimilarity  Homogeneity    Energy  \
0     100_in.jpg  20.724252       2.288088     0.438872  0.081312   
1     101_in.jpg  16.771010       2.028503     0.473208  0.070399   
2     102_in.jpg  15.290466       2.097700     0.476175  0.078554   
3     103_in.jpg  13.393222       1.949827     0.478556  0.082709   
4     104_in.jpg  48.865317       4.597472     0.217400  0.024069   
..           ...        ...            ...          ...       ...   
327  APB1_in.jpg  11.630805       2.283377     0.392207  0.027161   
328  APF1_in.jpg  16.828418       2.590653     0.367775  0.023200   
329  API1_in.jpg  24.070237       3.077826     0.338018  0.020702   
330  APT1_in.jpg  11.374251       2.212526     0.411023  0.027651   
331  APV1_in.jpg  17.921893       2.674031     0.383695  0.044775   

     Correlation   Entropy  
0       0.992157  6.803283  
1       0.992393  6.553655  
2       0.993845  6.623045  
3       0.994228  6.703817  
4       0.969792  6.784765  
..           ...       ...  
327     0.996672  7.372829  
328     0.996779  7.648864  
329     0.996248  7.747142  
330     0.997420  7.514703  
331     0.997229  7.634049  

[332 rows x 7 columns]

In [10]:
final=pd.merge(glcm, df_img, on='Image Name')
final

Image Name   Contrast  Dissimilarity  Homogeneity    Energy  \
0     100_in.jpg  20.724252       2.288088     0.438872  0.081312   
1     101_in.jpg  16.771010       2.028503     0.473208  0.070399   
2     102_in.jpg  15.290466       2.097700     0.476175  0.078554   
3     103_in.jpg  13.393222       1.949827     0.478556  0.082709   
4     104_in.jpg  48.865317       4.597472     0.217400  0.024069   
..           ...        ...            ...          ...       ...   
316  APB1_in.jpg  11.630805       2.283377     0.392207  0.027161   
317  APF1_in.jpg  16.828418       2.590653     0.367775  0.023200   
318  API1_in.jpg  24.070237       3.077826     0.338018  0.020702   
319  APT1_in.jpg  11.374251       2.212526     0.411023  0.027651   
320  APV1_in.jpg  17.921893       2.674031     0.383695  0.044775   

     Correlation   Entropy  Aceto Uptake  
0       0.992157  6.803283           2.0  
1       0.992393  6.553655           2.0  
2       0.993845  6.623045           2.0  
3       0.994228  6.703817           2.0  
4       0.969792  6.784765           2.0  
..           ...       ...           ...  
316     0.996672  7.372829           0.0  
317     0.996779  7.648864           0.0  
318     0.996248  7.747142           0.0  
319     0.997420  7.514703           0.0  
320     0.997229  7.634049           0.0  

[321 rows x 8 columns]

In [20]:
X=final.iloc[:,1:7]
X.head()

Contrast  Dissimilarity  Homogeneity    Energy  Correlation   Entropy
0  20.724252       2.288088     0.438872  0.081312     0.992157  6.803283
1  16.771010       2.028503     0.473208  0.070399     0.992393  6.553655
2  15.290466       2.097700     0.476175  0.078554     0.993845  6.623045
3  13.393222       1.949827     0.478556  0.082709     0.994228  6.703817
4  48.865317       4.597472     0.217400  0.024069     0.969792  6.784765

In [21]:
Y=final["Aceto Uptake"]
Y.head()

0    2.0
1    2.0
2    2.0
3    2.0
4    2.0
Name: Aceto Uptake, dtype: float64

In [22]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test= train_test_split(X,Y, random_state=100, test_size=0.2)
y_train.head()


299    0.0
157    0.0
110    1.0
208    2.0
191    0.0
Name: Aceto Uptake, dtype: float64

In [23]:
import time
from sklearn.svm import SVC 
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
svm = SVC(kernel = 'linear', C = 1)
svm.fit(x_train, y_train) 
start=time.time()
svm_predictions = svm.predict(x_test) 
# model accuracy for X_test   
accuracy = svm.score(x_test, y_test)

# creating a confusion matrix 
cm = confusion_matrix(y_test, svm_predictions) 
print("Accuracy of SVM is:",accuracy)
end=time.time()
print("Time taken:", end - start) 
print(cm)

Accuracy of SVM is: 0.5538461538461539
Time taken: 0.013718843460083008
[[ 0  1 23]
 [ 0  3  5]
 [ 0  0 33]]


In [24]:
from sklearn.ensemble import RandomForestClassifier
model=RandomForestClassifier(n_estimators=25)
model.fit(x_train,y_train)
preds=model.predict(x_test)
acc=accuracy_score(y_test,preds)
print("The Accuracy of randomforestclassifier is:", acc)

parameters = {
    "n_estimators":[5,10,50,100,250],
    "max_depth":[2,4,8,16,32,None]
}

from sklearn.model_selection import GridSearchCV
cv = GridSearchCV(model,parameters,cv=5)
start=time.time()
cv.fit(x_train,y_train)
end=time.time()
print("The best accuracy score obtained is:",cv.best_score_," at parameters ", cv.best_params_)
print("Time taken:", end-start)


The Accuracy of randomforestclassifier is: 0.676923076923077
The best accuracy score obtained is: 0.6875565610859729  at parameters  {'max_depth': 16, 'n_estimators': 50}
Time taken: 36.79357194900513


In [25]:
from sklearn.ensemble import RandomForestClassifier
model=RandomForestClassifier(n_estimators=50)
model.fit(x_train,y_train)
preds=model.predict(x_test)
acc=accuracy_score(y_test,preds)
print("The Accuracy of randomforestclassifier is:", acc)
cm = confusion_matrix(y_test, preds) 
print(cm)

The Accuracy of randomforestclassifier is: 0.7076923076923077
[[19  0  5]
 [ 0  5  3]
 [ 9  2 22]]


In [26]:
from sklearn.ensemble import GradientBoostingClassifier

model= GradientBoostingClassifier()
start=time.time()
model.fit(x_train,y_train)
end=time.time()
preds=model.predict(x_test)
acc=accuracy_score(y_test, preds)
print("Accuracy:", acc)
print("Time taken:", end-start)
cm = confusion_matrix(y_test, preds) 
print(cm)

Accuracy: 0.6153846153846154
Time taken: 1.0490410327911377
[[17  0  7]
 [ 1  3  4]
 [10  3 20]]


In [34]:
from sklearn.naive_bayes import GaussianNB
model=GaussianNB()
start=time.time()
model.fit(x_train,y_train)
end=time.time()
preds=model.predict(x_test)
acc=accuracy_score(y_test,preds)
print("The Accuracy of Naive Bayes is:", acc)
print("Time:", end-start)
cm = confusion_matrix(y_test, preds) 
print(cm)

The Accuracy of Naive Bayes is: 0.7230769230769231
Time: 0.009386301040649414
[[21  1  2]
 [ 0  6  2]
 [11  2 20]]


In [28]:
from sklearn.linear_model import LogisticRegression
model=LogisticRegression()
start=time.time()
model.fit(x_train,y_train)
end=time.time()
preds=model.predict(x_test)
acc=accuracy_score(y_test,preds)
print("The Accuracy of Logistic regression is:", acc)
print("Time:", end-start)
cm = confusion_matrix(y_test, preds) 
print(cm)

The Accuracy of Logistic regression is: 0.5230769230769231
Time: 0.041875600814819336
[[ 6  1 17]
 [ 0  5  3]
 [ 9  1 23]]


c:\Users\sakth\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [11]:
final=final[final["Aceto Uptake"]!=1.0]
final


Image Name   Contrast  Dissimilarity  Homogeneity    Energy  \
0     100_in.jpg  20.724252       2.288088     0.438872  0.081312   
1     101_in.jpg  16.771010       2.028503     0.473208  0.070399   
2     102_in.jpg  15.290466       2.097700     0.476175  0.078554   
3     103_in.jpg  13.393222       1.949827     0.478556  0.082709   
4     104_in.jpg  48.865317       4.597472     0.217400  0.024069   
..           ...        ...            ...          ...       ...   
316  APB1_in.jpg  11.630805       2.283377     0.392207  0.027161   
317  APF1_in.jpg  16.828418       2.590653     0.367775  0.023200   
318  API1_in.jpg  24.070237       3.077826     0.338018  0.020702   
319  APT1_in.jpg  11.374251       2.212526     0.411023  0.027651   
320  APV1_in.jpg  17.921893       2.674031     0.383695  0.044775   

     Correlation   Entropy  Aceto Uptake  
0       0.992157  6.803283           2.0  
1       0.992393  6.553655           2.0  
2       0.993845  6.623045           2.0  
3       0.994228  6.703817           2.0  
4       0.969792  6.784765           2.0  
..           ...       ...           ...  
316     0.996672  7.372829           0.0  
317     0.996779  7.648864           0.0  
318     0.996248  7.747142           0.0  
319     0.997420  7.514703           0.0  
320     0.997229  7.634049           0.0  

[273 rows x 8 columns]

In [12]:

X=final.iloc[:,1:7]
X.head()


Contrast  Dissimilarity  Homogeneity    Energy  Correlation   Entropy
0  20.724252       2.288088     0.438872  0.081312     0.992157  6.803283
1  16.771010       2.028503     0.473208  0.070399     0.992393  6.553655
2  15.290466       2.097700     0.476175  0.078554     0.993845  6.623045
3  13.393222       1.949827     0.478556  0.082709     0.994228  6.703817
4  48.865317       4.597472     0.217400  0.024069     0.969792  6.784765

In [13]:

Y=final["Aceto Uptake"]
Y.head()


0    2.0
1    2.0
2    2.0
3    2.0
4    2.0
Name: Aceto Uptake, dtype: float64

In [14]:


from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test= train_test_split(X,Y, random_state=100, test_size=0.2)
y_train.head()



159    0.0
239    2.0
29     2.0
147    2.0
256    0.0
Name: Aceto Uptake, dtype: float64

In [15]:

import time
from sklearn.svm import SVC 
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
svm = SVC(kernel = 'linear', C = 1)
svm.fit(x_train, y_train) 
start=time.time()
svm_predictions = svm.predict(x_test) 
# model accuracy for X_test   
accuracy = svm.score(x_test, y_test)

# creating a confusion matrix 
cm = confusion_matrix(y_test, svm_predictions) 
print("Accuracy of SVM is:",accuracy)
end=time.time()
print("Time taken:", end - start) 
print(cm)



Accuracy of SVM is: 0.6181818181818182
Time taken: 0.00769495964050293
[[ 0 21]
 [ 0 34]]


In [16]:

from sklearn.ensemble import RandomForestClassifier
model=RandomForestClassifier(n_estimators=25)
model.fit(x_train,y_train)
preds=model.predict(x_test)
acc=accuracy_score(y_test,preds)
print("The Accuracy of randomforestclassifier is:", acc)

parameters = {
    "n_estimators":[5,10,50,100,250],
    "max_depth":[2,4,8,16,32,None]
}

from sklearn.model_selection import GridSearchCV
cv = GridSearchCV(model,parameters,cv=5)
start=time.time()
cv.fit(x_train,y_train)
end=time.time()
print("The best accuracy score obtained is:",cv.best_score_," at parameters ", cv.best_params_)
print("Time taken:", end-start)


The Accuracy of randomforestclassifier is: 0.8181818181818182
The best accuracy score obtained is: 0.7938689217758985  at parameters  {'max_depth': None, 'n_estimators': 10}
Time taken: 27.720145225524902


In [17]:


from sklearn.ensemble import RandomForestClassifier
model=RandomForestClassifier(n_estimators=50)
model.fit(x_train,y_train)
preds=model.predict(x_test)
acc=accuracy_score(y_test,preds)
print("The Accuracy of randomforestclassifier is:", acc)
cm = confusion_matrix(y_test, preds) 
print(cm)



The Accuracy of randomforestclassifier is: 0.7818181818181819
[[18  3]
 [ 9 25]]


In [18]:

from sklearn.ensemble import GradientBoostingClassifier

model= GradientBoostingClassifier()
start=time.time()
model.fit(x_train,y_train)
end=time.time()
preds=model.predict(x_test)
acc=accuracy_score(y_test, preds)
print("Accuracy:", acc)
print("Time taken:", end-start)
cm = confusion_matrix(y_test, preds) 
print(cm)



Accuracy: 0.7272727272727273
Time taken: 0.3431077003479004
[[15  6]
 [ 9 25]]


In [19]:

from sklearn.naive_bayes import GaussianNB
model=GaussianNB()
start=time.time()
model.fit(x_train,y_train)
end=time.time()
preds=model.predict(x_test)
acc=accuracy_score(y_test,preds)
print("The Accuracy of Naive Bayes is:", acc)
print("Time:", end-start)
cm = confusion_matrix(y_test, preds) 
print(cm)



The Accuracy of Naive Bayes is: 0.6181818181818182
Time: 0.001990795135498047
[[ 7 14]
 [ 7 27]]


In [20]:

from sklearn.linear_model import LogisticRegression
model=LogisticRegression()
start=time.time()
model.fit(x_train,y_train)
end=time.time()
preds=model.predict(x_test)
acc=accuracy_score(y_test,preds)
print("The Accuracy of Logistic regression is:", acc)
print("Time:", end-start)
cm = confusion_matrix(y_test, preds) 
print(cm)

The Accuracy of Logistic regression is: 0.6363636363636364
Time: 0.03153252601623535
[[ 2 19]
 [ 1 33]]
