In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_excel('Labelled_DATA(1).xlsx')
df

Case No. Unnamed: 1 Aceto Image Name      Vessel Image Name  \
0           1        NaN              NaN                    NaN   
1           2        NaN              NaN  2.1_2.jpg , 2.2_4.jpg   
2           3        NaN              NaN                    NaN   
3           4        NaN              NaN              4.2_4.jpg   
4           5        NaN              NaN              5.1_1.jpg   
..        ...        ...              ...                    ...   
386       387        AAR         AAR1.jpg                    NaN   
387       388        AEY         AEY1.jpg                    NaN   
388       389        AEU         AEU1.jpg                    NaN   
389       390        ADF         ADF1.jpg                    NaN   
390       391        ABK         ABK1.jpg                    NaN   

     Lugol Image Name  Unnamed: 5  Aceto Uptake  Margins  Vessels  \
0                 NaN         NaN           2.0      NaN      NaN   
1             2_5.jpg         NaN           2.0      2.0      1.0   
2             3_3.jpg         NaN           2.0      NaN      NaN   
3             4_5.jpg         NaN           2.0      NaN      2.0   
4             5_4.jpg         NaN           2.0      NaN      1.0   
..                ...         ...           ...      ...      ...   
386               NaN         NaN           2.0      NaN      NaN   
387               NaN         NaN           2.0      NaN      NaN   
388               NaN         NaN           2.0      NaN      NaN   
389               NaN         NaN           2.0      NaN      NaN   
390               NaN         NaN           2.0      NaN      NaN   

     Lesion Size  Iodine Uptake  Unnamed: 11  Swede Score  
0            NaN            NaN          NaN          NaN  
1            1.0            2.0          NaN          8.0  
2            NaN            2.0          NaN          9.0  
3            NaN            2.0          NaN         10.0  
4            NaN            2.0          NaN          9.0  
..           ...            ...          ...          ...  
386          NaN            NaN          NaN          NaN  
387          NaN            NaN          NaN          NaN  
388          NaN            NaN          NaN          NaN  
389          NaN            NaN          NaN          NaN  
390          NaN            NaN          NaN          NaN  

[391 rows x 13 columns]

In [3]:
df=df.iloc[45:390, :]
df

Case No. Unnamed: 1 Aceto Image Name Vessel Image Name  Lugol Image Name  \
45         46        NaN           46.jpg               NaN               NaN   
46         47        NaN           47.jpg               NaN               NaN   
47         48        NaN           48.jpg               NaN               NaN   
48         49        NaN           49.jpg               NaN               NaN   
49         50        NaN           50.jpg               NaN               NaN   
..        ...        ...              ...               ...               ...   
385       386        AAC         AAC1.jpg               NaN               NaN   
386       387        AAR         AAR1.jpg               NaN               NaN   
387       388        AEY         AEY1.jpg               NaN               NaN   
388       389        AEU         AEU1.jpg               NaN               NaN   
389       390        ADF         ADF1.jpg               NaN               NaN   

     Unnamed: 5  Aceto Uptake  Margins  Vessels  Lesion Size  Iodine Uptake  \
45          NaN           0.0      NaN      NaN          NaN            NaN   
46          NaN           0.0      NaN      NaN          NaN            NaN   
47          NaN           0.0      NaN      NaN          NaN            NaN   
48          NaN           0.0      NaN      NaN          NaN            NaN   
49          NaN           0.0      NaN      NaN          NaN            NaN   
..          ...           ...      ...      ...          ...            ...   
385         NaN           2.0      NaN      NaN          NaN            NaN   
386         NaN           2.0      NaN      NaN          NaN            NaN   
387         NaN           2.0      NaN      NaN          NaN            NaN   
388         NaN           2.0      NaN      NaN          NaN            NaN   
389         NaN           2.0      NaN      NaN          NaN            NaN   

     Unnamed: 11  Swede Score  
45           NaN          NaN  
46           NaN          NaN  
47           NaN          NaN  
48           NaN          NaN  
49           NaN          NaN  
..           ...          ...  
385          NaN          NaN  
386          NaN          NaN  
387          NaN          NaN  
388          NaN          NaN  
389          NaN          NaN  

[345 rows x 13 columns]

In [4]:
df_img=df[["Aceto Image Name","Aceto Uptake"]]
df_img

Aceto Image Name  Aceto Uptake
45            46.jpg           0.0
46            47.jpg           0.0
47            48.jpg           0.0
48            49.jpg           0.0
49            50.jpg           0.0
..               ...           ...
385         AAC1.jpg           2.0
386         AAR1.jpg           2.0
387         AEY1.jpg           2.0
388         AEU1.jpg           2.0
389         ADF1.jpg           2.0

[345 rows x 2 columns]

In [5]:
df_img=df_img.dropna()
df_img

Aceto Image Name  Aceto Uptake
45            46.jpg           0.0
46            47.jpg           0.0
47            48.jpg           0.0
48            49.jpg           0.0
49            50.jpg           0.0
..               ...           ...
385         AAC1.jpg           2.0
386         AAR1.jpg           2.0
387         AEY1.jpg           2.0
388         AEU1.jpg           2.0
389         ADF1.jpg           2.0

[322 rows x 2 columns]

In [6]:
def update_img_name(img_name):
    return img_name.replace('.jpg', '_in_crop1.jpg')
df_img['Aceto Image Name'] = df_img['Aceto Image Name'].apply(update_img_name)

C:\Users\sakth\AppData\Local\Temp\ipykernel_18328\2103408140.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_img['Aceto Image Name'] = df_img['Aceto Image Name'].apply(update_img_name)


In [7]:
df_img

Aceto Image Name  Aceto Uptake
45     46_in_crop1.jpg           0.0
46     47_in_crop1.jpg           0.0
47     48_in_crop1.jpg           0.0
48     49_in_crop1.jpg           0.0
49     50_in_crop1.jpg           0.0
..                 ...           ...
385  AAC1_in_crop1.jpg           2.0
386  AAR1_in_crop1.jpg           2.0
387  AEY1_in_crop1.jpg           2.0
388  AEU1_in_crop1.jpg           2.0
389  ADF1_in_crop1.jpg           2.0

[322 rows x 2 columns]

In [8]:
df_img.rename(columns={"Aceto Image Name": "Image Name"},inplace=True)
df_img

C:\Users\sakth\AppData\Local\Temp\ipykernel_18328\835848021.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_img.rename(columns={"Aceto Image Name": "Image Name"},inplace=True)


Image Name  Aceto Uptake
45     46_in_crop1.jpg           0.0
46     47_in_crop1.jpg           0.0
47     48_in_crop1.jpg           0.0
48     49_in_crop1.jpg           0.0
49     50_in_crop1.jpg           0.0
..                 ...           ...
385  AAC1_in_crop1.jpg           2.0
386  AAR1_in_crop1.jpg           2.0
387  AEY1_in_crop1.jpg           2.0
388  AEU1_in_crop1.jpg           2.0
389  ADF1_in_crop1.jpg           2.0

[322 rows x 2 columns]

In [9]:
glcm= pd.read_excel('glcm_crop_inpaint.xlsx')
glcm.sort_values('Image Name')
glcm

Image Name   Contrast  Dissimilarity  Homogeneity    Energy  \
0     100_in_crop1.jpg  27.982177       1.781212     0.617627  0.305107   
1     101_in_crop1.jpg  11.116904       1.411999     0.646516  0.325888   
2     102_in_crop1.jpg   8.773512       1.291987     0.664615  0.345073   
3     103_in_crop1.jpg  15.987535       1.433897     0.635116  0.310985   
4     104_in_crop1.jpg  39.971201       2.550133     0.505603  0.291744   
..                 ...        ...            ...          ...       ...   
327  APB1_in_crop1.jpg  52.756175       1.373601     0.741660  0.577333   
328  APF1_in_crop1.jpg  45.238075       1.705130     0.709723  0.578086   
329  API1_in_crop1.jpg  52.051286       1.538793     0.739723  0.576728   
330  APT1_in_crop1.jpg  28.442770       1.155037     0.750684  0.579216   
331  APV1_in_crop1.jpg  32.702702       1.452100     0.723859  0.578388   

     Correlation   Entropy  
0       0.991997  5.566528  
1       0.995484  5.456143  
2       0.996179  5.304478  
3       0.993799  5.563552  
4       0.991016  5.525430  
..           ...       ...  
327     0.995646  4.020864  
328     0.994467  4.156965  
329     0.996438  4.159901  
330     0.997371  4.004521  
331     0.997175  4.121513  

[332 rows x 7 columns]

In [10]:
final=pd.merge(glcm, df_img, on='Image Name')
final

Image Name   Contrast  Dissimilarity  Homogeneity    Energy  \
0     100_in_crop1.jpg  27.982177       1.781212     0.617627  0.305107   
1     101_in_crop1.jpg  11.116904       1.411999     0.646516  0.325888   
2     102_in_crop1.jpg   8.773512       1.291987     0.664615  0.345073   
3     103_in_crop1.jpg  15.987535       1.433897     0.635116  0.310985   
4     104_in_crop1.jpg  39.971201       2.550133     0.505603  0.291744   
..                 ...        ...            ...          ...       ...   
316  APB1_in_crop1.jpg  52.756175       1.373601     0.741660  0.577333   
317  APF1_in_crop1.jpg  45.238075       1.705130     0.709723  0.578086   
318  API1_in_crop1.jpg  52.051286       1.538793     0.739723  0.576728   
319  APT1_in_crop1.jpg  28.442770       1.155037     0.750684  0.579216   
320  APV1_in_crop1.jpg  32.702702       1.452100     0.723859  0.578388   

     Correlation   Entropy  Aceto Uptake  
0       0.991997  5.566528           2.0  
1       0.995484  5.456143           2.0  
2       0.996179  5.304478           2.0  
3       0.993799  5.563552           2.0  
4       0.991016  5.525430           2.0  
..           ...       ...           ...  
316     0.995646  4.020864           0.0  
317     0.994467  4.156965           0.0  
318     0.996438  4.159901           0.0  
319     0.997371  4.004521           0.0  
320     0.997175  4.121513           0.0  

[321 rows x 8 columns]

In [12]:
X=final.iloc[:,1:7]
X.head()

Contrast  Dissimilarity  Homogeneity    Energy  Correlation   Entropy
0  27.982177       1.781212     0.617627  0.305107     0.991997  5.566528
1  11.116904       1.411999     0.646516  0.325888     0.995484  5.456143
2   8.773512       1.291987     0.664615  0.345073     0.996179  5.304478
3  15.987535       1.433897     0.635116  0.310985     0.993799  5.563552
4  39.971201       2.550133     0.505603  0.291744     0.991016  5.525430

In [13]:
Y=final["Aceto Uptake"]
Y.head()

0    2.0
1    2.0
2    2.0
3    2.0
4    2.0
Name: Aceto Uptake, dtype: float64

In [40]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test= train_test_split(X,Y, random_state=100, test_size=0.2)
y_train.head()


KeyboardInterrupt: 

In [15]:
import time
from sklearn.svm import SVC 
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
svm = SVC(kernel = 'linear', C = 1)
svm.fit(x_train, y_train) 
start=time.time()
svm_predictions = svm.predict(x_test) 
# model accuracy for X_test   
accuracy = svm.score(x_test, y_test)

# creating a confusion matrix 
cm = confusion_matrix(y_test, svm_predictions) 
print("Accuracy of SVM is:",accuracy)
end=time.time()
print("Time taken:", end - start) 
print(cm)

Accuracy of SVM is: 0.6461538461538462
Time taken: 0.008069753646850586
[[17  0  7]
 [ 0  0  8]
 [ 8  0 25]]


In [16]:
from sklearn.ensemble import RandomForestClassifier
model=RandomForestClassifier(n_estimators=25)
model.fit(x_train,y_train)
preds=model.predict(x_test)
acc=accuracy_score(y_test,preds)
print("The Accuracy of randomforestclassifier is:", acc)

parameters = {
    "n_estimators":[5,10,50,100,250],
    "max_depth":[2,4,8,16,32,None]
}

from sklearn.model_selection import GridSearchCV
cv = GridSearchCV(model,parameters,cv=5)
start=time.time()
cv.fit(x_train,y_train)
end=time.time()
print("The best accuracy score obtained is:",cv.best_score_," at parameters ", cv.best_params_)
print("Time taken:", end-start)


The Accuracy of randomforestclassifier is: 0.7076923076923077
The best accuracy score obtained is: 0.6683257918552036  at parameters  {'max_depth': 16, 'n_estimators': 100}
Time taken: 33.58903431892395


In [18]:
from sklearn.ensemble import RandomForestClassifier
model=RandomForestClassifier(n_estimators=50)
model.fit(x_train,y_train)
preds=model.predict(x_test)
acc=accuracy_score(y_test,preds)
print("The Accuracy of randomforestclassifier is:", acc)
cm = confusion_matrix(y_test, preds) 
print(cm)

The Accuracy of randomforestclassifier is: 0.7230769230769231
[[18  0  6]
 [ 1  5  2]
 [ 7  2 24]]


In [19]:
from sklearn.ensemble import GradientBoostingClassifier

model= GradientBoostingClassifier()
start=time.time()
model.fit(x_train,y_train)
end=time.time()
preds=model.predict(x_test)
acc=accuracy_score(y_test, preds)
print("Accuracy:", acc)
print("Time taken:", end-start)
cm = confusion_matrix(y_test, preds) 
print(cm)

Accuracy: 0.6307692307692307
Time taken: 1.204183578491211
[[16  1  7]
 [ 1  4  3]
 [10  2 21]]


In [14]:
from sklearn.naive_bayes import GaussianNB
model=GaussianNB()
start=time.time()
model.fit(x_train,y_train)
end=time.time()
preds=model.predict(x_test)
acc=accuracy_score(y_test,preds)
print("The Accuracy of Naive Bayes is:", acc)
print("Time:", end-start)
cm = confusion_matrix(y_test, preds) 
print(cm)

The Accuracy of Naive Bayes is: 0.5675675675675675
Time: 0.004060506820678711
[[15  5]
 [11  6]]


In [20]:
from sklearn.linear_model import LogisticRegression
model=LogisticRegression()
start=time.time()
model.fit(x_train,y_train)
end=time.time()
preds=model.predict(x_test)
acc=accuracy_score(y_test,preds)
print("The Accuracy of Logistic regression is:", acc)
print("Time:", end-start)
cm = confusion_matrix(y_test, preds) 
print(cm)

The Accuracy of Logistic regression is: 0.5230769230769231
Time: 0.07646894454956055
[[12  0 12]
 [ 0  0  8]
 [ 9  2 22]]


c:\Users\sakth\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [11]:
final["Aceto Uptake"].unique()

array([2., 1., 0.])

In [12]:
final=final[final["Aceto Uptake"]!=1.0]
final

Image Name   Contrast  Dissimilarity  Homogeneity    Energy  \
0     100_in_crop1.jpg  27.982177       1.781212     0.617627  0.305107   
1     101_in_crop1.jpg  11.116904       1.411999     0.646516  0.325888   
2     102_in_crop1.jpg   8.773512       1.291987     0.664615  0.345073   
3     103_in_crop1.jpg  15.987535       1.433897     0.635116  0.310985   
4     104_in_crop1.jpg  39.971201       2.550133     0.505603  0.291744   
..                 ...        ...            ...          ...       ...   
316  APB1_in_crop1.jpg  52.756175       1.373601     0.741660  0.577333   
317  APF1_in_crop1.jpg  45.238075       1.705130     0.709723  0.578086   
318  API1_in_crop1.jpg  52.051286       1.538793     0.739723  0.576728   
319  APT1_in_crop1.jpg  28.442770       1.155037     0.750684  0.579216   
320  APV1_in_crop1.jpg  32.702702       1.452100     0.723859  0.578388   

     Correlation   Entropy  Aceto Uptake  
0       0.991997  5.566528           2.0  
1       0.995484  5.456143           2.0  
2       0.996179  5.304478           2.0  
3       0.993799  5.563552           2.0  
4       0.991016  5.525430           2.0  
..           ...       ...           ...  
316     0.995646  4.020864           0.0  
317     0.994467  4.156965           0.0  
318     0.996438  4.159901           0.0  
319     0.997371  4.004521           0.0  
320     0.997175  4.121513           0.0  

[273 rows x 8 columns]

In [13]:
X=final.iloc[:,1:7]
X.head()

Contrast  Dissimilarity  Homogeneity    Energy  Correlation   Entropy
0  27.982177       1.781212     0.617627  0.305107     0.991997  5.566528
1  11.116904       1.411999     0.646516  0.325888     0.995484  5.456143
2   8.773512       1.291987     0.664615  0.345073     0.996179  5.304478
3  15.987535       1.433897     0.635116  0.310985     0.993799  5.563552
4  39.971201       2.550133     0.505603  0.291744     0.991016  5.525430

In [14]:
Y=final["Aceto Uptake"]
Y.head()


0    2.0
1    2.0
2    2.0
3    2.0
4    2.0
Name: Aceto Uptake, dtype: float64

In [15]:

from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test= train_test_split(X,Y, random_state=100, test_size=0.2)
y_train.head()


159    0.0
239    2.0
29     2.0
147    2.0
256    0.0
Name: Aceto Uptake, dtype: float64

In [43]:

import time
from sklearn.svm import SVC 
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
svm = SVC(kernel = 'linear', C = 1)
svm.fit(x_train, y_train) 
start=time.time()
svm_predictions = svm.predict(x_test) 
# model accuracy for X_test   
accuracy = svm.score(x_test, y_test)

# creating a confusion matrix 
cm = confusion_matrix(y_test, svm_predictions) 
print("Accuracy of SVM is:",accuracy)
end=time.time()
print("Time taken:", end - start) 
print(cm)


Accuracy of SVM is: 0.8
Time taken: 0.0014052391052246094
[[20  1]
 [10 24]]


In [44]:

from sklearn.ensemble import RandomForestClassifier
model=RandomForestClassifier(n_estimators=25)
model.fit(x_train,y_train)
preds=model.predict(x_test)
acc=accuracy_score(y_test,preds)
print("The Accuracy of randomforestclassifier is:", acc)

parameters = {
    "n_estimators":[5,10,50,100,250],
    "max_depth":[2,4,8,16,32,None]
}

from sklearn.model_selection import GridSearchCV
cv = GridSearchCV(model,parameters,cv=5)
start=time.time()
cv.fit(x_train,y_train)
end=time.time()
print("The best accuracy score obtained is:",cv.best_score_," at parameters ", cv.best_params_)
print("Time taken:", end-start)


The Accuracy of randomforestclassifier is: 0.7636363636363637
The best accuracy score obtained is: 0.7250528541226215  at parameters  {'max_depth': 4, 'n_estimators': 50}
Time taken: 34.900444746017456


In [45]:

from sklearn.ensemble import RandomForestClassifier
model=RandomForestClassifier(n_estimators=50)
model.fit(x_train,y_train)
preds=model.predict(x_test)
acc=accuracy_score(y_test,preds)
print("The Accuracy of randomforestclassifier is:", acc)
cm = confusion_matrix(y_test, preds) 
print(cm)


The Accuracy of randomforestclassifier is: 0.7636363636363637
[[16  5]
 [ 8 26]]


In [46]:

from sklearn.ensemble import GradientBoostingClassifier

model= GradientBoostingClassifier()
start=time.time()
model.fit(x_train,y_train)
end=time.time()
preds=model.predict(x_test)
acc=accuracy_score(y_test, preds)
print("Accuracy:", acc)
print("Time taken:", end-start)
cm = confusion_matrix(y_test, preds) 
print(cm)


Accuracy: 0.6909090909090909
Time taken: 0.24511384963989258
[[14  7]
 [10 24]]


In [48]:

from sklearn.naive_bayes import GaussianNB
model=GaussianNB()
start=time.time()
model.fit(x_train,y_train)
end=time.time()
preds=model.predict(x_test)
acc=accuracy_score(y_test,preds)
print("The Accuracy of Naive Bayes is:", acc)
print("Time:", end-start)
cm = confusion_matrix(y_test, preds) 
print(cm)


The Accuracy of Naive Bayes is: 0.6
Time: 0.0044972896575927734
[[20  1]
 [21 13]]


In [18]:

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix
model=LogisticRegression()
model.fit(x_train,y_train)
preds=model.predict(x_test)
acc=accuracy_score(y_test,preds)
print("The Accuracy of Logistic regression is:", acc)
cm = confusion_matrix(y_test, preds) 
print(cm)

The Accuracy of Logistic regression is: 0.8545454545454545
[[18  3]
 [ 5 29]]


In [ ]:
import pickle
pickle.dump(model,  open("acetic_2class_in_c_logistic", 'wb'))