In [11]:
import pandas as pd
import numpy as np

In [12]:
df=pd.read_excel('Labelled_DATA(1).xlsx')
df

Case No. Unnamed: 1 Aceto Image Name      Vessel Image Name  \
0           1        NaN              NaN                    NaN   
1           2        NaN              NaN  2.1_2.jpg , 2.2_4.jpg   
2           3        NaN              NaN                    NaN   
3           4        NaN              NaN              4.2_4.jpg   
4           5        NaN              NaN              5.1_1.jpg   
..        ...        ...              ...                    ...   
386       387        AAR         AAR1.jpg                    NaN   
387       388        AEY         AEY1.jpg                    NaN   
388       389        AEU         AEU1.jpg                    NaN   
389       390        ADF         ADF1.jpg                    NaN   
390       391        ABK         ABK1.jpg                    NaN   

     Lugol Image Name  Unnamed: 5  Aceto Uptake  Margins  Vessels  \
0                 NaN         NaN           2.0      NaN      NaN   
1             2_5.jpg         NaN           2.0      2.0      1.0   
2             3_3.jpg         NaN           2.0      NaN      NaN   
3             4_5.jpg         NaN           2.0      NaN      2.0   
4             5_4.jpg         NaN           2.0      NaN      1.0   
..                ...         ...           ...      ...      ...   
386               NaN         NaN           2.0      NaN      NaN   
387               NaN         NaN           2.0      NaN      NaN   
388               NaN         NaN           2.0      NaN      NaN   
389               NaN         NaN           2.0      NaN      NaN   
390               NaN         NaN           2.0      NaN      NaN   

     Lesion Size  Iodine Uptake  Unnamed: 11  Swede Score  
0            NaN            NaN          NaN          NaN  
1            1.0            2.0          NaN          8.0  
2            NaN            2.0          NaN          9.0  
3            NaN            2.0          NaN         10.0  
4            NaN            2.0          NaN          9.0  
..           ...            ...          ...          ...  
386          NaN            NaN          NaN          NaN  
387          NaN            NaN          NaN          NaN  
388          NaN            NaN          NaN          NaN  
389          NaN            NaN          NaN          NaN  
390          NaN            NaN          NaN          NaN  

[391 rows x 13 columns]

In [13]:
df=df.iloc[45:390, :]
df

Case No. Unnamed: 1 Aceto Image Name Vessel Image Name  Lugol Image Name  \
45         46        NaN           46.jpg               NaN               NaN   
46         47        NaN           47.jpg               NaN               NaN   
47         48        NaN           48.jpg               NaN               NaN   
48         49        NaN           49.jpg               NaN               NaN   
49         50        NaN           50.jpg               NaN               NaN   
..        ...        ...              ...               ...               ...   
385       386        AAC         AAC1.jpg               NaN               NaN   
386       387        AAR         AAR1.jpg               NaN               NaN   
387       388        AEY         AEY1.jpg               NaN               NaN   
388       389        AEU         AEU1.jpg               NaN               NaN   
389       390        ADF         ADF1.jpg               NaN               NaN   

     Unnamed: 5  Aceto Uptake  Margins  Vessels  Lesion Size  Iodine Uptake  \
45          NaN           0.0      NaN      NaN          NaN            NaN   
46          NaN           0.0      NaN      NaN          NaN            NaN   
47          NaN           0.0      NaN      NaN          NaN            NaN   
48          NaN           0.0      NaN      NaN          NaN            NaN   
49          NaN           0.0      NaN      NaN          NaN            NaN   
..          ...           ...      ...      ...          ...            ...   
385         NaN           2.0      NaN      NaN          NaN            NaN   
386         NaN           2.0      NaN      NaN          NaN            NaN   
387         NaN           2.0      NaN      NaN          NaN            NaN   
388         NaN           2.0      NaN      NaN          NaN            NaN   
389         NaN           2.0      NaN      NaN          NaN            NaN   

     Unnamed: 11  Swede Score  
45           NaN          NaN  
46           NaN          NaN  
47           NaN          NaN  
48           NaN          NaN  
49           NaN          NaN  
..           ...          ...  
385          NaN          NaN  
386          NaN          NaN  
387          NaN          NaN  
388          NaN          NaN  
389          NaN          NaN  

[345 rows x 13 columns]

In [14]:
df_img=df[["Aceto Image Name","Aceto Uptake"]]
df_img

Aceto Image Name  Aceto Uptake
45            46.jpg           0.0
46            47.jpg           0.0
47            48.jpg           0.0
48            49.jpg           0.0
49            50.jpg           0.0
..               ...           ...
385         AAC1.jpg           2.0
386         AAR1.jpg           2.0
387         AEY1.jpg           2.0
388         AEU1.jpg           2.0
389         ADF1.jpg           2.0

[345 rows x 2 columns]

In [15]:
df_img=df_img.dropna()
df_img

Aceto Image Name  Aceto Uptake
45            46.jpg           0.0
46            47.jpg           0.0
47            48.jpg           0.0
48            49.jpg           0.0
49            50.jpg           0.0
..               ...           ...
385         AAC1.jpg           2.0
386         AAR1.jpg           2.0
387         AEY1.jpg           2.0
388         AEU1.jpg           2.0
389         ADF1.jpg           2.0

[322 rows x 2 columns]

In [16]:
def update_img_name(img_name):
    return img_name.replace('.jpg', '_crop1.jpg')
df_img['Aceto Image Name'] = df_img['Aceto Image Name'].apply(update_img_name)

C:\Users\sakth\AppData\Local\Temp\ipykernel_16084\3163568558.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_img['Aceto Image Name'] = df_img['Aceto Image Name'].apply(update_img_name)


In [17]:
df_img

Aceto Image Name  Aceto Uptake
45      46_crop1.jpg           0.0
46      47_crop1.jpg           0.0
47      48_crop1.jpg           0.0
48      49_crop1.jpg           0.0
49      50_crop1.jpg           0.0
..               ...           ...
385   AAC1_crop1.jpg           2.0
386   AAR1_crop1.jpg           2.0
387   AEY1_crop1.jpg           2.0
388   AEU1_crop1.jpg           2.0
389   ADF1_crop1.jpg           2.0

[322 rows x 2 columns]

In [18]:
df_img.rename(columns={"Aceto Image Name": "Image Name"},inplace=True)
df_img

C:\Users\sakth\AppData\Local\Temp\ipykernel_16084\835848021.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_img.rename(columns={"Aceto Image Name": "Image Name"},inplace=True)


Image Name  Aceto Uptake
45     46_crop1.jpg           0.0
46     47_crop1.jpg           0.0
47     48_crop1.jpg           0.0
48     49_crop1.jpg           0.0
49     50_crop1.jpg           0.0
..              ...           ...
385  AAC1_crop1.jpg           2.0
386  AAR1_crop1.jpg           2.0
387  AEY1_crop1.jpg           2.0
388  AEU1_crop1.jpg           2.0
389  ADF1_crop1.jpg           2.0

[322 rows x 2 columns]

In [19]:
glcm= pd.read_excel('glcm_c.xlsx')
glcm

Image Name   Contrast  Dissimilarity  Homogeneity    Energy  \
0     100_crop1.jpg  84.429094       2.684642     0.588899  0.304578   
1     101_crop1.jpg  25.861247       1.816722     0.635213  0.328270   
2     102_crop1.jpg  14.350678       1.517383     0.656063  0.345339   
3     103_crop1.jpg  44.190923       2.107242     0.604583  0.312246   
4     104_crop1.jpg  45.213213       2.692847     0.499668  0.292023   
..              ...        ...            ...          ...       ...   
327  APB1_crop1.jpg  65.755842       1.645858     0.734995  0.577304   
328  APF1_crop1.jpg  53.252427       1.820339     0.710071  0.578399   
329  API1_crop1.jpg  58.298390       1.695070     0.733172  0.576779   
330  APT1_crop1.jpg  37.167127       1.362281     0.749347  0.579226   
331  APV1_crop1.jpg  47.980243       1.754545     0.718107  0.578286   

     Correlation   Entropy  
0       0.982329  5.691272  
1       0.990288  5.478900  
2       0.994487  5.354519  
3       0.989684  5.752810  
4       0.989948  5.540677  
..           ...       ...  
327     0.994709  4.074182  
328     0.993934  4.193638  
329     0.996058  4.188905  
330     0.996711  4.015172  
331     0.995942  4.161142  

[332 rows x 7 columns]

In [20]:
final=pd.merge(glcm, df_img, on='Image Name')
final

Image Name   Contrast  Dissimilarity  Homogeneity    Energy  \
0     100_crop1.jpg  84.429094       2.684642     0.588899  0.304578   
1     101_crop1.jpg  25.861247       1.816722     0.635213  0.328270   
2     102_crop1.jpg  14.350678       1.517383     0.656063  0.345339   
3     103_crop1.jpg  44.190923       2.107242     0.604583  0.312246   
4     104_crop1.jpg  45.213213       2.692847     0.499668  0.292023   
..              ...        ...            ...          ...       ...   
316  APB1_crop1.jpg  65.755842       1.645858     0.734995  0.577304   
317  APF1_crop1.jpg  53.252427       1.820339     0.710071  0.578399   
318  API1_crop1.jpg  58.298390       1.695070     0.733172  0.576779   
319  APT1_crop1.jpg  37.167127       1.362281     0.749347  0.579226   
320  APV1_crop1.jpg  47.980243       1.754545     0.718107  0.578286   

     Correlation   Entropy  Aceto Uptake  
0       0.982329  5.691272           2.0  
1       0.990288  5.478900           2.0  
2       0.994487  5.354519           2.0  
3       0.989684  5.752810           2.0  
4       0.989948  5.540677           2.0  
..           ...       ...           ...  
316     0.994709  4.074182           0.0  
317     0.993934  4.193638           0.0  
318     0.996058  4.188905           0.0  
319     0.996711  4.015172           0.0  
320     0.995942  4.161142           0.0  

[321 rows x 8 columns]

In [21]:
X=final.iloc[:,1:7]
X.head()

Contrast  Dissimilarity  Homogeneity    Energy  Correlation   Entropy
0  84.429094       2.684642     0.588899  0.304578     0.982329  5.691272
1  25.861247       1.816722     0.635213  0.328270     0.990288  5.478900
2  14.350678       1.517383     0.656063  0.345339     0.994487  5.354519
3  44.190923       2.107242     0.604583  0.312246     0.989684  5.752810
4  45.213213       2.692847     0.499668  0.292023     0.989948  5.540677

In [22]:
Y=final["Aceto Uptake"]
Y.head()

0    2.0
1    2.0
2    2.0
3    2.0
4    2.0
Name: Aceto Uptake, dtype: float64

In [23]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test= train_test_split(X,Y, random_state=100, test_size=0.2)
y_train.head()


299    0.0
157    0.0
110    1.0
208    2.0
191    0.0
Name: Aceto Uptake, dtype: float64

In [24]:
import time
from sklearn.svm import SVC 
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
svm = SVC(kernel = 'linear', C = 1)
svm.fit(x_train, y_train) 
start=time.time()
svm_predictions = svm.predict(x_test) 
# model accuracy for X_test   
accuracy = svm.score(x_test, y_test)

# creating a confusion matrix 
cm = confusion_matrix(y_test, svm_predictions) 
print("Accuracy of SVM is:",accuracy)
end=time.time()
print("Time taken:", end - start) 
print(cm)

Accuracy of SVM is: 0.6
Time taken: 0.006016731262207031
[[18  0  6]
 [ 0  0  8]
 [12  0 21]]


In [25]:
from sklearn.ensemble import RandomForestClassifier
model=RandomForestClassifier(n_estimators=25)
model.fit(x_train,y_train)
preds=model.predict(x_test)
acc=accuracy_score(y_test,preds)
print("The Accuracy of randomforestclassifier is:", acc)

parameters = {
    "n_estimators":[5,10,50,100,250],
    "max_depth":[2,4,8,16,32,None]
}

from sklearn.model_selection import GridSearchCV
cv = GridSearchCV(model,parameters,cv=5)
start=time.time()
cv.fit(x_train,y_train)
end=time.time()
print("The best accuracy score obtained is:",cv.best_score_," at parameters ", cv.best_params_)
print("Time taken:", end-start)


The Accuracy of randomforestclassifier is: 0.6307692307692307
The best accuracy score obtained is: 0.637028657616893  at parameters  {'max_depth': 4, 'n_estimators': 250}
Time taken: 32.13398766517639


In [26]:
from sklearn.ensemble import RandomForestClassifier
model=RandomForestClassifier(n_estimators=50)
model.fit(x_train,y_train)
preds=model.predict(x_test)
acc=accuracy_score(y_test,preds)
print("The Accuracy of randomforestclassifier is:", acc)
cm = confusion_matrix(y_test, preds) 
print(cm)

The Accuracy of randomforestclassifier is: 0.7230769230769231
[[17  0  7]
 [ 0  7  1]
 [ 9  1 23]]


In [27]:
from sklearn.ensemble import GradientBoostingClassifier

model= GradientBoostingClassifier()
start=time.time()
model.fit(x_train,y_train)
end=time.time()
preds=model.predict(x_test)
acc=accuracy_score(y_test, preds)
print("Accuracy:", acc)
print("Time taken:", end-start)
cm = confusion_matrix(y_test, preds) 
print(cm)

Accuracy: 0.6615384615384615
Time taken: 1.0175790786743164
[[16  1  7]
 [ 0  4  4]
 [10  0 23]]


In [28]:
from sklearn.naive_bayes import GaussianNB
model=GaussianNB()
start=time.time()
model.fit(x_train,y_train)
end=time.time()
preds=model.predict(x_test)
acc=accuracy_score(y_test,preds)
print("The Accuracy of Naive Bayes is:", acc)
print("Time:", end-start)
cm = confusion_matrix(y_test, preds) 
print(cm)

The Accuracy of Naive Bayes is: 0.49230769230769234
Time: 0.0026102066040039062
[[21  1  2]
 [ 0  8  0]
 [18 12  3]]


In [29]:
from sklearn.linear_model import LogisticRegression
model=LogisticRegression()
start=time.time()
model.fit(x_train,y_train)
end=time.time()
preds=model.predict(x_test)
acc=accuracy_score(y_test,preds)
print("The Accuracy of Logistic regression is:", acc)
print("Time:", end-start)
cm = confusion_matrix(y_test, preds) 
print(cm)

The Accuracy of Logistic regression is: 0.5538461538461539
Time: 0.04098367691040039
[[15  0  9]
 [ 0  0  8]
 [12  0 21]]


c:\Users\sakth\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [30]:
final=final[final["Aceto Uptake"]!=1.0]
final


Image Name   Contrast  Dissimilarity  Homogeneity    Energy  \
0     100_crop1.jpg  84.429094       2.684642     0.588899  0.304578   
1     101_crop1.jpg  25.861247       1.816722     0.635213  0.328270   
2     102_crop1.jpg  14.350678       1.517383     0.656063  0.345339   
3     103_crop1.jpg  44.190923       2.107242     0.604583  0.312246   
4     104_crop1.jpg  45.213213       2.692847     0.499668  0.292023   
..              ...        ...            ...          ...       ...   
316  APB1_crop1.jpg  65.755842       1.645858     0.734995  0.577304   
317  APF1_crop1.jpg  53.252427       1.820339     0.710071  0.578399   
318  API1_crop1.jpg  58.298390       1.695070     0.733172  0.576779   
319  APT1_crop1.jpg  37.167127       1.362281     0.749347  0.579226   
320  APV1_crop1.jpg  47.980243       1.754545     0.718107  0.578286   

     Correlation   Entropy  Aceto Uptake  
0       0.982329  5.691272           2.0  
1       0.990288  5.478900           2.0  
2       0.994487  5.354519           2.0  
3       0.989684  5.752810           2.0  
4       0.989948  5.540677           2.0  
..           ...       ...           ...  
316     0.994709  4.074182           0.0  
317     0.993934  4.193638           0.0  
318     0.996058  4.188905           0.0  
319     0.996711  4.015172           0.0  
320     0.995942  4.161142           0.0  

[273 rows x 8 columns]

In [31]:

X=final.iloc[:,1:7]
X.head()


Contrast  Dissimilarity  Homogeneity    Energy  Correlation   Entropy
0  84.429094       2.684642     0.588899  0.304578     0.982329  5.691272
1  25.861247       1.816722     0.635213  0.328270     0.990288  5.478900
2  14.350678       1.517383     0.656063  0.345339     0.994487  5.354519
3  44.190923       2.107242     0.604583  0.312246     0.989684  5.752810
4  45.213213       2.692847     0.499668  0.292023     0.989948  5.540677

In [32]:

Y=final["Aceto Uptake"]
Y.head()


0    2.0
1    2.0
2    2.0
3    2.0
4    2.0
Name: Aceto Uptake, dtype: float64

In [33]:


from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test= train_test_split(X,Y, random_state=100, test_size=0.2)
y_train.head()



159    0.0
239    2.0
29     2.0
147    2.0
256    0.0
Name: Aceto Uptake, dtype: float64

In [34]:

import time
from sklearn.svm import SVC 
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
svm = SVC(kernel = 'linear', C = 1)
svm.fit(x_train, y_train) 
start=time.time()
svm_predictions = svm.predict(x_test) 
# model accuracy for X_test   
accuracy = svm.score(x_test, y_test)

# creating a confusion matrix 
cm = confusion_matrix(y_test, svm_predictions) 
print("Accuracy of SVM is:",accuracy)
end=time.time()
print("Time taken:", end - start) 
print(cm)



Accuracy of SVM is: 0.7090909090909091
Time taken: 0.006482124328613281
[[17  4]
 [12 22]]


In [35]:

from sklearn.ensemble import RandomForestClassifier
model=RandomForestClassifier(n_estimators=25)
model.fit(x_train,y_train)
preds=model.predict(x_test)
acc=accuracy_score(y_test,preds)
print("The Accuracy of randomforestclassifier is:", acc)

parameters = {
    "n_estimators":[5,10,50,100,250],
    "max_depth":[2,4,8,16,32,None]
}

from sklearn.model_selection import GridSearchCV
cv = GridSearchCV(model,parameters,cv=5)
start=time.time()
cv.fit(x_train,y_train)
end=time.time()
print("The best accuracy score obtained is:",cv.best_score_," at parameters ", cv.best_params_)
print("Time taken:", end-start)



The Accuracy of randomforestclassifier is: 0.7090909090909091
The best accuracy score obtained is: 0.7709302325581395  at parameters  {'max_depth': 16, 'n_estimators': 50}
Time taken: 28.367990732192993


In [42]:

from sklearn.ensemble import RandomForestClassifier
model=RandomForestClassifier(n_estimators=50, max_depth=16)
model.fit(x_train,y_train)
preds=model.predict(x_test)
acc=accuracy_score(y_test,preds)
print("The Accuracy of randomforestclassifier is:", acc)
cm = confusion_matrix(y_test, preds) 
print(cm)



The Accuracy of randomforestclassifier is: 0.7818181818181819
[[16  5]
 [ 7 27]]


In [37]:

from sklearn.ensemble import GradientBoostingClassifier

model= GradientBoostingClassifier()
start=time.time()
model.fit(x_train,y_train)
end=time.time()
preds=model.predict(x_test)
acc=accuracy_score(y_test, preds)
print("Accuracy:", acc)
print("Time taken:", end-start)
cm = confusion_matrix(y_test, preds) 
print(cm)



Accuracy: 0.7090909090909091
Time taken: 0.35404419898986816
[[15  6]
 [10 24]]


In [38]:

from sklearn.naive_bayes import GaussianNB
model=GaussianNB()
start=time.time()
model.fit(x_train,y_train)
end=time.time()
preds=model.predict(x_test)
acc=accuracy_score(y_test,preds)
print("The Accuracy of Naive Bayes is:", acc)
print("Time:", end-start)
cm = confusion_matrix(y_test, preds) 
print(cm)



The Accuracy of Naive Bayes is: 0.6
Time: 0.004594326019287109
[[20  1]
 [21 13]]


In [39]:

from sklearn.linear_model import LogisticRegression
model=LogisticRegression()
start=time.time()
model.fit(x_train,y_train)
end=time.time()
preds=model.predict(x_test)
acc=accuracy_score(y_test,preds)
print("The Accuracy of Logistic regression is:", acc)
print("Time:", end-start)
cm = confusion_matrix(y_test, preds) 
print(cm)

The Accuracy of Logistic regression is: 0.7454545454545455
Time: 0.03946256637573242
[[16  5]
 [ 9 25]]
